Talk(0, "Anh Vương, anh ổn chứ?", "talkname0", 1);
Talk(17, "Bạn là ai?", "talkname17", 0);
Talk(0, "Tôi được tiền bối Hồ ủy thác đến giải cứu bạn.", "talkname0", 1);
Talk(17, "thực tế? Còn bà ngoại Kim Hoa thì sao?", "talkname17", 0);
Talk(0, "Tiền bối yên tâm, lão bà kia đã bị ta đánh bại, tạm thời ta sẽ không làm khó ngươi.", "talkname0", 1);
Talk(17, "Cảm ơn sự giúp đỡ của bạn, người hùng trẻ tuổi. Vợ chồng tôi sẽ không bao giờ quên lòng tốt của bạn...", "talkname17", 0);
Talk(0, "Dù ở đâu, ở đâu đường gập ghềnh, rút kiếm ra giúp đỡ là điều mà những người thuộc thế hệ chúng ta nên làm. Hiện tại chuyện này đã xong, ta còn có việc khác phải làm, tiền bối có thể rời đi trước.", "talkname0", 1);
Talk(17, "Được rồi, vậy ta trước tiên quay về Thung lũng Bướm, khi anh hùng trẻ tuổi rảnh rỗi nhất định phải đến Thung lũng Bướm của ta với tư cách là khách. Bạn phải đến! Vợ chồng tôi phải cho cô thứ gì đó để trả ơn cô.", "talkname17", 0);
Talk(0, "Lão bước đi chậm rãi.", "talkname0", 1);
ModifyEvent(-2, -2, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
jyx2_ReplaceSceneObject("", "NPC/王难姑", ""); 
ModifyEvent(44, 1, 1, 1, 123, -1, -1, 5290, 5290, 5290, -2, -2, -2);
jyx2_ReplaceSceneObject("44", "NPC/王难姑", "1"); 
ModifyEvent(44, 0, -2, -2, 95, -1, -1, -2, -2, -2, -2, -2, -2);
DarkScence();
LightScence();
AddEthics(3);
do return end;
