Talk(0, "Huh! Tại sao bốn người lại ở đây?", "talkname0", 1);
Talk(73, "Xin chúc mừng, chàng trai trẻ. Sau bao khó khăn, cuối cùng bạn cũng đã đến được đây. Nó chứng tỏ việc thực hành của bạn đã đạt được kết quả.", "talkname73", 0);
Talk(74, "Bạn trẻ, những lời khuyên tôi đưa ra cho bạn có thể vẫn hữu ích.", "talkname74", 0);
Talk(75, "Cái gì, ngươi còn muốn ăn đồ ăn do Lâm đầu bếp của ta nấu sao? Hay bạn muốn về nhà thật nhanh và ăn những món mẹ nấu?", "talkname75", 0);
Talk(72, "Tôi, Kong Bala, thực sự bị bạn thuyết phục. Ngay cả mười bậc thầy hàng đầu làm việc cùng nhau cũng không thể sánh được với bạn. Tốt cho bạn. \"Quyền trượng võ thuật\" này đã được trả lại cho bạn và bạn thực sự xứng đáng với nó.", "talkname72", 0);
Talk(0, "Bốn người các bạn là...", "talkname0", 1);
Talk(74, "Bạn có thấy bốn người chúng ta rất kỳ lạ không?", "talkname74", 0);
Talk(0, "Có một điều như thế...đặc biệt là...", "talkname0", 1);
Talk(72, "Đặc biệt là tôi, Kong Bala!", "talkname72", 0);
Talk(0, "Vâng, thật kỳ lạ. Bạn là ai?", "talkname0", 1);
Talk(75, "Chúng ta đang ở ngoài “bầy đàn”. Nói cách khác, họ là những người ở ngoài thế giới trò chơi này.", "talkname75", 0);
Talk(72, "Trên thực tế, chúng tôi có biệt danh là \"Tứ đại vương của ngành game\". Và thủ lĩnh của chúng tôi chính là “búp bê mềm mại” trong nhà bạn. Vì vậy, bạn hiểu.", "talkname72", 0);
Talk(0, "Ồ! Hóa ra bạn là...", "talkname0", 1);
Talk(73, "Được rồi, tôi sẽ không lãng phí thời gian quý báu của bạn. Đi xuống sâu hơn là kết thúc trò chơi. Một số người trong chúng tôi ở đây để tiễn bạn theo lệnh của tù trưởng và chuyển lại vài lời cho bạn. Tôi hy vọng trò chơi này có thể làm cho bạn vui vẻ và hạnh phúc. Tận hưởng niềm vui mà một người chơi nên có. Nhưng nếu không, tôi hy vọng bạn có thể viết thư cho chúng tôi và chỉ ra những điều chúng tôi chưa nhận thấy. Bằng cách này, chúng tôi có thể cải thiện vào lần sau để đáp ứng yêu cầu của bạn. Ngoài ra, \"ngoại truyện\" của trò chơi này cũng đang được sản xuất, hy vọng sớm được gặp lại bạn, có thể bạn sẽ lại là người tiêu dùng \"may mắn nhất\". Nhưng điều này còn phụ thuộc vào sự hỗ trợ của các bạn. Hãy viết thư để cho tôi lời khuyên và động viên.", "talkname73", 0);
DarkScence();
ModifyEvent(-2, 35, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
ModifyEvent(-2, 36, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
ModifyEvent(-2, 37, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
ModifyEvent(-2, 38, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
jyx2_ReplaceSceneObject("", "NPC/四大金刚", "");
LightScence();
Talk(0, "Bây giờ thực sự không có ai ở đây nên tôi phải về nhà!", "talkname0", 1);
AddItem(143, 1);
ModifyEvent(-2, 6, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
ModifyEvent(-2, 7, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
ModifyEvent(-2, 8, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
ModifyEvent(-2, 9, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
ModifyEvent(-2, 10, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
do return end;
