Talk(0, "Vị đại ca này, núi sông ở đây đẹp hùng vĩ, không biết nơi này đóng quân của môn phái nào.", "talkname0", 1);
Talk(79, "Chàng trai, đây là núi Kongtong, nơi mà môn phái Kongtong của tôi luyện tập võ thuật và duy trì sức khỏe, tôi còn chưa biết điều này và vẫn ra ngoài chơi.", "talkname79", 0);
Talk(0, "Người em mới làm quen với thế giới, kiến thức còn ít nên mong nhận được lời khuyên từ anh trai.", "talkname0", 1);
Talk(79, "Tôi nhớ năm đó, sư phụ của tôi, Mu Lingzi, đã gây chấn động thế giới với một bộ Thất Thương Quyền, trở nên nổi tiếng khắp thế giới, nó đã đặt nền móng cho môn phái Kongtong của chúng ta trong hàng trăm năm và được xếp hạng trong sáu giáo phái lớn trong thế giới võ thuật ngày nay.", "talkname79", 0);
Talk(0, "Sáu giáo phái lớn?", "talkname0", 1);
Talk(79, "Đúng! Có sáu giáo phái lớn: Thiếu Lâm, Võ Đang, Khổng Đồng, Nga Mi, Côn Lôn và Hoa Sơn.", "talkname79", 0);
Talk(0, "Đó là nó! Vậy thì tôi thực sự muốn gặp người đứng đầu giáo phái của bạn. Xem Bảy vết thương, kỹ năng độc đáo của Giáo phái Kongtong.", "talkname0", 1);
Talk(79, "Sư phụ có thể không nhìn thấy ngươi, bởi vì sáu đại giáo phái của chúng ta hiện tại đang bận tấn công Ma giáo. Nhưng bạn cũng có thể đi vào và thử vận may của mình.", "talkname79", 0);
ModifyEvent(-2, 1, -2, -2, 125, -1, -1, -2, -2, -2, -2, -2, -2);
ModifyEvent(-2, 2, -2, -2, 125, -1, -1, -2, -2, -2, -2, -2, -2);
ModifyEvent(-2, 3, -2, -2, 125, -1, -1, -2, -2, -2, -2, -2, -2);
ModifyEvent(-2, 4, -2, -2, 125, -1, -1, -2, -2, -2, -2, -2, -2);
ModifyEvent(-2, 5, -2, -2, 125, -1, -1, -2, -2, -2, -2, -2, -2);
ModifyEvent(-2, 6, -2, -2, 125, -1, -1, -2, -2, -2, -2, -2, -2);
ModifyEvent(-2, 7, -2, -2, 125, -1, -1, -2, -2, -2, -2, -2, -2);
do return end;
