Talk(0, "Tiền bối là Trương Tam Phong sư phụ, tiểu bối tới chào hỏi.", "talkname0", 1);
Talk(5, "Đó chỉ là tuổi già thôi.", "talkname5", 0);
Talk(0, "Vị thiếu niên này thực sự rất vinh dự được gặp tiền bối Zhang. Phải biết người dân ở đó rất kính trọng sư phụ, có thể nói trong lịch sử võ thuật Trung Quốc, ông là một cao thủ vĩ đại kế thừa quá khứ và mở ra tương lai.", "talkname0", 1);
Talk(5, "Ở đâu, ở đâu. Tôi tự hỏi em trai đến từ đâu?", "talkname5", 0);
Talk(0, "Ngay cả các bậc thầy cũng có thể không hiểu được, bởi vì các bạn ngày nay có thể không hiểu được. Tôi đến từ một thế giới khác, nơi những thứ như bạn chỉ là huyền thoại. Mình nói thế này chắc các tiền bối sẽ không hiểu đâu!", "talkname0", 1);
Talk(5, "Tôi nhớ khi còn nhỏ, tôi đã gặp một người đàn ông xa lạ cùng với người thầy quá cố của tôi Jue Yuan, lời nói của bạn có vẻ giống với lời nói của anh ấy.", "talkname5", 0);
Talk(0, "Cậu cũng đã gặp anh ấy rồi! Tôi cũng nghe mọi người nói về anh ấy nên muốn tìm thứ gì đó để xem có giúp được gì cho mình không.", "talkname0", 1);
Talk(5, "Em trai nhắc đến một vài cuốn sách.", "talkname5", 0);
Talk(0, "Người cao tuổi cũng biết về “Sách Mười Bốn Ngày”? Không biết các tiền bối có biết những cuốn sách này ở đâu không?", "talkname0", 1);
Talk(5, "Lão Chấn đã xa xứ đã lâu nên không biết những cuốn sách này tung tích ở đâu. Em trai có vẻ háo hức muốn có được những cuốn sách này?", "talkname5", 0);
Talk(0, "Những cuốn sách này sẽ giúp ích rất nhiều cho “tương lai” của tôi nên tôi rất háo hức muốn tìm thấy hết. Thật không may, mọi người trên thế giới luôn cho rằng những cuốn sách này là bí quyết võ học sâu sắc nào đó, vì vậy sau một trận chiến khốc liệt giữa bạn và tôi, tôi không biết những cuốn sách này hiện đang ở đâu. Nhưng theo tôi được biết, những cuốn sách này không phải là bí quyết võ học.", "talkname0", 1);
Talk(5, "Trên thực tế, rèn luyện võ thuật ban đầu chỉ là một cách để tăng cường thể chất nhưng hiện nay người ta lại sử dụng nó như một công cụ để cạnh tranh, đây thực sự là một quan niệm sai lầm.", "talkname5", 0);
Talk(0, "Nhưng tôi nghĩ võ thuật đôi khi cũng khá hữu ích. Giống như khi tôi bước đi trên thế giới, nếu không có võ công mạnh mẽ, có lẽ tôi đã chết từ lâu.", "talkname0", 1);
Talk(5, "Tốt! Nếu không có ai giỏi võ hơn ai thì trên thế giới sẽ ít giết chóc hơn rất nhiều.", "talkname5", 0);
Talk(0, "Nhưng đôi khi việc rèn luyện võ thuật có thể hấp dẫn mọi người, giống như chơi cờ vậy. Tuy nhiên, khi chứng minh võ công, việc gây tổn hại về thể chất sẽ dễ dàng hơn.", "talkname0", 1);
Talk(5, "Đối với những người luyện võ, ngoài việc phấn đấu để bề ngoài mạnh mẽ thì điều quan trọng hơn chính là cái tâm của người võ sĩ. Người luyện võ phải biết kiềm chế ham muốn chiến đấu, luôn giữ tấm lòng hào hiệp, diệt trừ cái ác và thực thi công lý, giúp đỡ kẻ yếu và hỗ trợ kẻ yếu, sử dụng võ thuật ở nơi cần sử dụng. Đây mới là ý nghĩa thực sự của võ thuật. đào tạo nghệ thuật.", "talkname5", 0);
Talk(0, "Những gì tiền bối nói hoàn toàn là sự thật, hậu bối sẽ nhớ mãi.", "talkname0", 1);
Talk(5, "Nếu bạn có thể duy trì trái tim hào hiệp trong suốt hành trình đến thế giới, tôi sẵn sàng so tài với bạn về võ thuật. Hãy xem liệu nó có thể giúp ích gì cho bạn không nhé.", "talkname5", 0);
Talk(0, "Thật sự? Thế hệ trẻ sẽ được hưởng lợi từ điều đó trong suốt cuộc đời nếu họ có thể nhận được sự hướng dẫn từ những người đi trước.", "talkname0", 1);
Talk(5, "Hãy nhớ một điều, người luyện võ phải luôn giữ tấm lòng hào hiệp.", "talkname5", 0);
ModifyEvent(-2, -2, -2, -2, 155, -1, -1, -2, -2, -2, -2, -2, -2);
do return end;
