ScenceFromTo(32, 33, 32, 24);
jyx2_CameraFollow("Level/NPC/miejueshitai");--by fanyu
Talk(6, "……….Giáo phái ma quỷ coi lửa là thiêng liêng và tôn trọng lửa như thần………. Kể từ khi thủ lĩnh thứ ba mươi ba của Ma Giáo, Dương Đỉnh Thiên đột ngột qua đời, hắn đã không còn xứng đáng với tư cách là người kế vị được chỉ định nữa. Các sứ giả ánh sáng bên trái và bên phải trong tôn giáo, bốn vị đại hộ pháp Pháp vương và năm người tản mác đều thèm muốn vị trí lãnh đạo của tôn giáo. Kết quả là họ chiến đấu chống lại nhau, và tà giáo từ đó suy tàn. Đây cũng là lúc sáu giáo phái cùng nhau thịnh vượng và những linh hồn tà ác sẽ bị tiêu diệt. Nếu ma giáo không đủ khả năng nội chiến thì sẽ rất khó để chọn ra những con quái vật này. Sáu đại giáo phái quyết tâm giành thắng lợi lần này khi tiến vào Quảng Minh Đỉnh, cho dù tất cả tà linh đều liên thủ, chúng ta có gì phải sợ? Chỉ là khi chiến đấu sẽ bị tổn thất rất lớn, mọi người phải quyết tâm chiến đấu đến chết, không thể mạo hiểm, sợ hãi, làm mất đi uy tín của Nga Mi phái khi đối mặt với kẻ thù. Tục ngữ có câu: "Nghìn quan tài ra khỏi cửa, gia đình thịnh vượng. Con trai sống sót trước khi cha chết, và cháu trai chết theo tổ tiên". Ai trong chúng ta là bất tử? Chỉ cần huyết mạch của con cháu còn lưu lại, gia tộc dù có chết hàng nghìn người vẫn có thể thịnh vượng. Điều tôi sợ nhất là các bạn đều đã chết, còn tôi, già ni lại sống một mình. Hehe, nhưng dù vậy cũng không đáng tiếc chút nào. Một trăm năm trước, trên thế giới không có giáo phái Nga Mi. Chỉ cần mọi người chiến đấu đến chết với tinh thần mạnh mẽ, thì giáo phái Nga Mi có bị tiêu diệt trong một đòn thì có ích gì?", "talkname6", 0);
Talk(77, "Các đệ tử thề sẽ chiến đấu đến chết và không tương thích với ma quỷ và đường ác.", "talkname77", 0);
Talk(6, "Tiểu đệ tử vô liêm sỉ, nghe lén đã đủ chưa?", "talkname6", 0);
ScenceFromTo(32, 24, 32, 33);
jyx2_CameraFollowPlayer();--by fanyu
Talk(0, "＜Tôi không muốn nghe những gì tôi nói nhiều đâu! > Vị tiểu bối này thật là thô lỗ, tôi tình cờ nghe được lời nói trịnh trọng và chính trực như vậy của sư phụ, không khỏi nghe theo. Người đàn em này sẽ bày tỏ lòng kính trọng đối với người đứng đầu Nga Mi.", "talkname0", 1);
ModifyEvent(-2, 0, -2, -2, -1, -1, -1, -2, -2, -2, -2, -2, -2);
ModifyEvent(-2, 1, -2, -2, -1, -1, -1, -2, -2, -2, -2, -2, -2);
ModifyEvent(-2, 11, -2, -2, -1, -1, 147, -2, -2, -2, -2, -2, -2);--by fanyu 启动脚本147 场景33-11
do return end;
