ScenceFromTo(41, 29, 33, 29);
jyx2_CameraFollow("Level/NPC/嵩山派/左冷禅");
Talk(22, "Chúng ta, Ngũ Sơn Kiếm Phái, đã liên thủ, đã liên minh hơn trăm năm, từ lâu đã như một gia đình. Anh Yan là thủ lĩnh của năm phe trong nhiều năm. Chỉ là gần đây giới võ lâm xảy ra rất nhiều sự kiện lớn, sau khi thảo luận với các vị tiền bối của Võ Việt Kiếm phái, các huynh đệ đều cảm thấy nếu không thành lập một môn phái duy nhất và ra lệnh thống nhất thì sẽ khó khăn. để chống lại thảm họa trong tương lai.", "talkname22", 0);
Talk(20, "Không biết lãnh đạo Tả Liên minh đã thảo luận với nhóm tiền bối nào? Sao tôi không biết chuyện gì đang xảy ra nhỉ?", "talkname20", 0);
Talk(22, "Anh vừa đề cập rằng nhiều sự kiện lớn đã xảy ra trong thế giới võ thuật, và năm phe phải hợp nhất thành một. Một trong những sự kiện lớn là năm phe của chúng ta đang giết hại lẫn nhau, bất chấp lòng trung thành của liên minh. Ông Mộ Đại, em trai tôi Phí, đệ tử của phái Tống Sơn, đã chết ở bên ngoài thành Hành Sơn. Có người tận mắt chứng kiến nói rằng chính ông Mộ Đa là kẻ giết người, không biết điều này có đúng không?", "talkname22", 0);
Talk(20, "Không có chuyện gì xảy ra! Thật tiếc khi nói rằng Mo Mou khiêm tốn như vậy, nhưng làm sao anh ta có thể giết được bàn tay lớn của Songyang?", "talkname20", 0);
Talk(22, "Anh Mặc, anh không cần quá lo lắng về vấn đề này, sau khi năm phe chúng ta hợp nhất, anh Mo và em cũng sẽ là anh em. Người chết không còn nữa, tại sao người sống lại tiếp tục phạm tội giết người và phạm thêm tội ác? Anh Mo, anh có nghĩ vậy không?", "talkname22", 0);
Talk(20, "khịt mũi!", "talkname20", 0);
Talk(22, "Phe Nanyue Hengshan không phản đối đề xuất sáp nhập các phe phái. Anh Tianmen của Dongyue Taishan Sect, anh nghĩ gì về giáo phái của mình?", "talkname22", 0);
Talk(23, "Đã hơn 300 năm kể từ khi Giáo phái Taishan được thành lập bởi người sáng lập, Đạo sĩ Dongling. Pindao không có đức hạnh và bất tài, không thể tiếp tục Thái Sơn phái, tuy nhiên, nền tảng hơn ba trăm năm không thể bị Pindao cắt đứt. Đề nghị sáp nhập các phe phái không bao giờ được tuân theo.", "talkname23", 0);
Talk(22, "Đạo hữu, điều này sai rồi. Sau khi hợp nhất năm giáo phái, phái Wuyue của chúng ta đã phát triển mạnh mẽ, đệ tử nào của nó sẽ không được hưởng lợi từ nó? Đạo sư vì lòng ích kỷ của mình với tư cách là người đứng đầu Thái Sơn giáo, tại sao phải cản trở đại sự của toàn tông?", "talkname22", 0);
Talk(23, "Là người lãnh đạo, tôi có làm hay không thì có quan trọng gì? Chỉ là phe Thái Sơn thôi, dù thế nào cũng không thể để người khác đoạt vào tay mình.", "talkname23", 0);
Talk(22, "Đạo huynh nói nhiều như vậy, nhưng trong lòng chỉ là không thể buông bỏ danh hiệu lãnh đạo.", "talkname22", 0);
Talk(23, "Bạn có thực sự biết rằng tôi rất ích kỷ? Được rồi, từ giờ trở đi tôi sẽ không còn là người lãnh đạo nữa...", "talkname23", 0);
Talk(22, "Anh Đào đồng ý với vấn đề này...", "talkname22", 0);
Talk(23, "Bạn…………", "talkname23", 0);
Talk(0, "<Lão đạo sĩ này quá nóng nảy và sẽ sa vào đường lối của người khác ngay khi bị khiêu khích. ＞", "talkname0", 1);
Talk(21, "Thủ lĩnh của liên minh Zuo đã là thủ lĩnh của Ngũ Sơn Kiếm Phái, địa vị của hắn được tôn trọng như vậy, tại sao phải sáp nhập năm giáo phái và để một người làm thủ lĩnh?", "talkname21", 0);
Talk(22, "Những gì thầy nói là sai. Zuo vừa đề xuất năm phe hợp nhất. Tất nhiên, vị trí lãnh đạo này phải do các thành viên trong năm giáo phái của chúng ta bầu ra.", "talkname22", 0);
ScenceFromTo(33, 29, 41, 29);
jyx2_CameraFollowPlayer();
WalkFromTo(41, 29, 35, 29);
jyx2_WalkFromTo(-1,3529);
Talk(0, "Tôi nghĩ chúng ta không nên bàn nữa, người học võ sẽ thấy được ý nghĩa thực sự của võ thuật. Thôi nào, nào, ai muốn đấu với tôi?", "talkname0", 1);
Talk(22, "Tôi không biết bạn là ai? Ngươi cư nhiên đột nhập vào Tống Sơn phái của chúng ta mà không có sự cho phép, ngươi không biết Ngũ Việt phái của chúng ta đang tụ tập ở đây sao?", "talkname22", 0);
Talk(19, "Vị anh hùng trẻ tuổi này đã đến núi Hoa Sơn của tôi cách đây vài ngày và tôi đã nhận anh ta vào phái Hoa Sơn của tôi.", "talkname19", 0);
Talk(22, "Hóa ra hắn là đệ tử của phái Hoa Sơn, theo lời này, Nhạc tiên sinh cũng đồng ý với phương pháp “dùng kiếm đánh đẹp trai” này?", "talkname22", 0);
Talk(19, "Đấu kiếm để thắng được trai đẹp cũng là một phương pháp, nhưng chỉ có thể làm để tránh làm tổn hại đến sự hòa hợp.", "talkname19", 0);
Talk(23, "Hóa ra Hoa Sơn phái ủng hộ việc sáp nhập nên tôi, Thiên Môn, sẽ đến trước để học những chiêu trò thông minh của Hoa Sơn phái.", "talkname23", 0);
Talk(35, "Thưa Thầy, hãy để các đệ tử đến.", "talkname35", 1);
if TryBattle(34) == true then goto label0 end;
    Dead();
    do return end;
::label0::
    LightScence();
    Talk(35, "Được chấp nhận, Đạo sĩ.", "talkname35", 1);
    Talk(21, "Hãy để tôi dành thời gian tìm hiểu những thủ thuật thông minh của phái Hoa Sơn.", "talkname21", 0);
    if TryBattle(35) == true then goto label1 end;
        Dead();
        do return end;
::label1::
        LightScence();
        Talk(35, "Đã nhận rồi, thưa Thầy. Tôi tự hỏi ai là người tiếp theo?", "talkname35", 1);
        Talk(20, "Bạn đã đánh hai trận liên tiếp nên hãy xuống nghỉ ngơi trước.", "talkname20", 0);
        Talk(35, "Không sao đâu, chàng trai trẻ tràn đầy nghị lực, xin hãy ra tay, Master Mo.", "talkname35", 1);
        if TryBattle(36) == true then goto label2 end;
            Dead();
            do return end;
::label2::
            LightScence();
            Talk(22, "Tục ngữ có câu: “Sóng sau sông Dương Tử đẩy sóng về phía trước”, ông Yue người Hoa Sơn chắc hẳn đã lên kế hoạch cho ngày hôm nay từ lâu. Nếu Zuo cũng bị đánh bại, giáo phái Songshan của chúng ta sẽ lấy ông Feng Yue làm thủ lĩnh.", "talkname22", 0);
            if TryBattle(37) == true then goto label3 end;
                Dead();
                do return end;
::label3::
                LightScence();
                Talk(35, "Cuối cùng cũng giải quyết được, mệt quá. Zuo Lengchan, xem ra âm mưu của ngươi không thể thực hiện được.", "talkname35", 1);
                Talk(22, "Tôi không nên đánh giá thấp bạn. Yue Buqun, không ngờ âm mưu của anh còn sâu xa hơn của tôi, Zuo đã đi trước anh một bước.", "talkname22", 0);
                Talk(0, "Vớ vẩn, anh Yue không muốn làm lãnh đạo. Lý do chính khiến tôi đến hôm nay là để ngăn chặn âm mưu của anh.", "talkname0", 1);
                Talk(22, "Anh Yue thực sự không muốn làm thủ lĩnh của Ngũ Sơn phái?", "talkname22", 0);
                Talk(19, "Đúng, tôi đã đề cập với vị anh hùng trẻ tuổi này rằng việc vội vã hợp nhất các phe phái khác nhau sẽ vô cùng khó khăn và sẽ dẫn đến tranh chấp võ thuật.", "talkname19", 0);
                Talk(0, "Bạn thấy đấy, những gì tôi nói là đúng.", "talkname0", 1);
                Talk(19, "Tuy nhiên, nếu các môn phái khác nhau có thể lựa chọn gần gũi về mặt địa lý, có võ công tương đồng hoặc có tình bạn tốt với nhau thì có thể hợp nhất trước. Trong vòng mười tám năm, số lượng môn phái sẽ giảm đi hơn một nửa. Sẽ ít rắc rối hơn nếu bạn dành thời gian. Wuyue Sword Sect của chúng ta hôm nay hòa nhập vào Wuyue Sect có thể làm gương cho mỗi môn phái, và trong tương lai chắc chắn sẽ trở thành một sự kiện hoành tráng vang danh khắp các thời đại trong giới võ thuật.", "talkname19", 0);
                Talk(0, "＜Sao mọi chuyện lại có thể thành ra thế này? Nó có vẻ khác với những gì tôi nghĩ! ＞", "talkname0", 1);
                Talk(19, "Được rồi, hôm nay Ngũ Việt Tông mới thành lập, có rất nhiều việc chờ đợi, ta chỉ có thể phụ trách việc của nó, việc của mỗi môn phái vẫn do những người đứng đầu ban đầu của mỗi môn phái chủ trì. Hôm nay Ngũ Thánh Tông chúng ta sáp nhập, nếu không thể hợp tác thành một, thì việc sáp nhập Ngũ Giáo chỉ là cái tên mà thôi. Ta vô đạo đức, bất tài, tạm thời nắm giữ tông môn của mình, về lâu dài phải bàn bạc mọi thay đổi với các huynh đệ, ta không dám hành động một mình. Bây giờ cũng đã muộn rồi, mọi người đều đã vất vả rồi, hôm nay chỉ vậy thôi, sau này chúng ta sẽ quay lại Hoa Sơn để cùng nhau bàn bạc những vấn đề quan trọng.", "talkname19", 0);
                Talk(19, "Sùng Nhi, sau khi xong việc hãy nhanh chóng quay lại Hoa Sơn. Cô chủ của bạn nhớ bạn rất nhiều.", "talkname19", 0);
                Talk(35, "Đúng!", "talkname35", 1);
                DarkScence();
                ModifyEvent(-2, 24, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
                ModifyEvent(-2, 25, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
                ModifyEvent(-2, 26, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
                ModifyEvent(-2, 27, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
                ModifyEvent(-2, 35, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
                ModifyEvent(-2, 36, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
                ModifyEvent(-2, 37, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
                ModifyEvent(-2, 38, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
                ModifyEvent(-2, 39, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
                ModifyEvent(-2, 40, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
                ModifyEvent(-2, 41, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
                ModifyEvent(-2, 42, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
                ModifyEvent(-2, 43, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
                ModifyEvent(-2, 44, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
                ModifyEvent(-2, 45, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
                ModifyEvent(-2, 46, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
                ModifyEvent(-2, 47, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
                ModifyEvent(-2, 48, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
                ModifyEvent(-2, 49, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
                ModifyEvent(-2, 50, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
				jyx2_ReplaceSceneObject("","NPC/五岳剑派","");
                ModifyEvent(-2, 2, -2, -2, 216, -1, -1, -2, -2, -2, -2, -2, -2);
                ModifyEvent(-2, 3, -2, -2, 216, -1, -1, -2, -2, -2, -2, -2, -2);
                ModifyEvent(-2, 14, -2, -2, 216, -1, -1, -2, -2, -2, -2, -2, -2);
                ModifyEvent(-2, 15, -2, -2, 216, -1, -1, -2, -2, -2, -2, -2, -2);
                ModifyEvent(-2, 16, -2, -2, 216, -1, -1, -2, -2, -2, -2, -2, -2);
                ModifyEvent(-2, 17, -2, -2, 216, -1, -1, -2, -2, -2, -2, -2, -2);
                ModifyEvent(-2, 18, -2, -2, 216, -1, -1, -2, -2, -2, -2, -2, -2);
                ModifyEvent(-2, 19, -2, -2, 216, -1, -1, -2, -2, -2, -2, -2, -2);
                ModifyEvent(-2, 20, -2, -2, 216, -1, -1, -2, -2, -2, -2, -2, -2);
                ModifyEvent(-2, 21, -2, -2, 216, -1, -1, -2, -2, -2, -2, -2, -2);
                ModifyEvent(-2, 22, -2, -2, 216, -1, -1, -2, -2, -2, -2, -2, -2);
                ModifyEvent(-2, 23, -2, -2, 216, -1, -1, -2, -2, -2, -2, -2, -2);
                ModifyEvent(-2, 29, -2, -2, 216, -1, -1, -2, -2, -2, -2, -2, -2);
                ModifyEvent(-2, 30, -2, -2, 216, -1, -1, -2, -2, -2, -2, -2, -2);
                ModifyEvent(-2, 31, -2, -2, 216, -1, -1, -2, -2, -2, -2, -2, -2);
                ModifyEvent(-2, 32, -2, -2, 216, -1, -1, -2, -2, -2, -2, -2, -2);
                ModifyEvent(-2, 33, -2, -2, 216, -1, -1, -2, -2, -2, -2, -2, -2);
                ModifyEvent(-2, 34, -2, -2, 216, -1, -1, -2, -2, -2, -2, -2, -2);
                ModifyEvent(-2, 28, -2, -2, 207, -1, -1, -2, -2, -2, -2, -2, -2);
                ModifyEvent(-2, 58, 0, 0, -1, -1, 218, -2, -2, -2, -2, -2, -2);
                ModifyEvent(-2, 59, 0, 0, -1, -1, 218, -2, -2, -2, -2, -2, -2);
                ModifyEvent(-2, 56, -2, -2, -1, -1, -1, -1, -1, -1, -2, -2, -2);
                ModifyEvent(-2, 57, -2, -2, -1, -1, -1, -1, -1, -1, -2, -2, -2);
                ModifyEvent(-2, 0, 0, 0, -1, -1, -1, -2, -2, -2, -2, -2, -2);
                LightScence();
do return end;
