Talk(0, "Xin chào! Bạn có muốn cạnh tranh với tôi không? Nếu vậy thì làm nhanh đi, tôi không có nhiều thời gian dành cho bạn đâu.", "talkname0", 1);
Talk(26, "Bạn là ai? Cậu đang làm gì ở đây ồn ào thế?", "talkname26", 0);
Talk(0, "Bạn còn hỏi tôi là ai, tôi là anh hùng trẻ tuổi đã đánh bại “Tứ bạn Mai Trang”. Ta nghe Nhị thôn chủ Hei Baizi nói ngươi muốn so tài với ta là bởi vì ngưỡng mộ võ công của ta phải không?", "talkname0", 1);
Talk(26, "ha! ha! Xem ra tuổi còn trẻ như vậy mà kiêu ngạo như vậy, không tệ! Tốt! Tôi thích. Bạn nói rằng bạn đã đánh bại bốn kẻ yếu đuối đó ở Meizhuang, bạn có nghiêm túc không?", "talkname26", 0);
Talk(0, "Tất nhiên đó là sự thật, tôi nghi ngờ điều đó!", "talkname0", 1);
Talk(0, "Thật kỳ lạ khi bạn nhốt mình trong hang động không nhìn thấy ánh sáng này, bạn bị bệnh! Hay là anh ta bị kích thích bởi điều gì đó?", "talkname0", 1);
Talk(26, "Tự nhốt mình ở đây? Tôi định nhốt mình trong ngục tối này à?", "talkname26", 0);
Talk(0, "＜Để tôi làm nhé? Hãy để tôi làm điều đó? Hình như tôi đã nghe cái tên này ở đâu đó. >Nhẫn tiền bối có bị giam ở đây không?", "talkname0", 1);
Talk(26, "Tôi xấu hổ khi nói rằng người lãnh đạo tôn nghiêm của Giáo phái Nhật Nguyệt Thần của tôi đang bị mắc kẹt ở đây.", "talkname26", 0);
Talk(0, "＜Lão già này là thủ lĩnh của Nhật Nguyệt Thần Giáo sao? Nhìn thế nào cũng không giống! ＞", "talkname0", 1);
Talk(26, "Nếu tôi không chuyên tâm luyện võ, tôi đã giao toàn bộ quyền lực trong tôn giáo cho Đông Phương Bất Bại. Không ngờ con sói bất bại phương Đông lại rất tham vọng, bề ngoài rất tôn trọng ta và không vi phạm điều gì, nhưng lại ngấm ngầm trau dồi quyền lực của bản thân và dùng nhiều lý do để loại bỏ hoặc xử tử tất cả cấp dưới trung thành với mình. tôi Chỉ trong vòng vài năm, Trong thời gian này, tất cả bạn bè thân thiết của tôi đều héo mòn. Thấy thời cơ đã đến, hắn lại lợi dụng ta luyện võ nhập quan, làm phản, cướp ngôi rồi giam ta dưới đáy Tây Hồ!", "talkname26", 0);
Talk(0, "Có một kẻ vô tâm như vậy, đừng để tôi gặp hắn, nếu không tôi nhất định phải cho hắn một cái nhìn rõ ràng.", "talkname0", 1);
Talk(26, "ha! ha! ha! Chỉ là bạn thôi, ha...!", "talkname26", 0);
Talk(0, "Ah…………", "talkname0", 1);
PlayAnimation(-1, 5974, 5992);
jyx2_PlayTimeline("[Timeline]ka37_药王山庄_晕倒", 0, false, "");
jyx2_Wait(2);
DarkScence();
jyx2_StopTimeline("[Timeline]ka37_药王山庄_晕倒");
AddItemWithoutHint(177, -1);
AddItemWithoutHint(178, -1);
AddItemWithoutHint(179, -1);
AddItemWithoutHint(180, -1);
ModifyEvent(-2, 1, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
jyx2_ReplaceSceneObject("", "NPC/renwoxing", "");--任我行逃走
jyx2_PlayTimeline("[Timeline]ka37_药王山庄_苏醒", 0, false, "");
LightScence();
jyx2_Wait(2);
PlayAnimation(-1, 6014, 6024);
jyx2_StopTimeline("[Timeline]ka37_药王山庄_苏醒");
Talk(0, "Lão già chết tiệt, hắn lợi dụng sự không chuẩn bị của tôi để tấn công tôi...ah! Kho báu của tôi! Tôi đã bị lừa! Nhất định là bốn tên hèn hạ đó, bọn chúng rõ ràng không đánh được ta, mà lại lén lút tới đây làm việc. Thật là vô liêm sỉ và tục tĩu.", "talkname0", 1);
Talk(0, "Nơi này là cái quái gì vậy? sự kỳ lạ? Lão già vừa rồi đột nhiên gầm lên... Ôi! Nhất định là bốn tên trộm đó, bọn họ không thể công khai đánh ta, nhưng lại lén lút tới đây. Thật là vô liêm sỉ và tục tĩu. Huh? Cánh cửa đang mở và có vẻ như tôi không bị khóa ở đây. Ừm, thực sự đáng nghi à? Có vẻ như chúng ta cần phải quan sát kỹ nơi ma quái này!", "talkname0", 1);
jyx2_StopTimeline("[Timeline]ka37_药王山庄_苏醒");
ModifyEvent(55, 20, 1, 1, -1, -1, -1, 6060, 6060, 6060, -2, -2, -2);
ModifyEvent(55, 21, 1, 1, -1, -1, -1, 6050, 6050, 6050, -2, -2, -2);
ModifyEvent(55, 22, 1, 1, -1, -1, -1, 6062, 6062, 6062, -2, -2, -2);
ModifyEvent(55, 23, 1, 1, -1, -1, -1, 6074, 6074, 6074, -2, -2, -2);
ModifyEvent(55, 24, 0, 0, -1, -1, 275, -1, -1, -1, -2, -2, -2);
jyx2_FixMapObject("任我行逃出地牢",1);
--jyx2_SwitchRoleAnimation("NPC/tubiweng", "Assets/BuildSource/AnimationControllers/自然站立Controller.controller");不能修改非当前场景模型，移动到275中执行
--jyx2_SwitchRoleAnimation("NPC/huangzhonggong", "Assets/BuildSource/AnimationControllers/自然站立Controller.controller");
ModifyEvent(-2, 3, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
ModifyEvent(-2, 4, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
ModifyEvent(-2, 5, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
ModifyEvent(-2, 6, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
ModifyEvent(-2, 7, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
AddEthics(2);
do return end;
