Talk(33, "Anh hùng trẻ tuổi, đã lâu không gặp, cậu thế nào rồi?", "talkname33", 0);
Talk(0, "<Lịch sự như vậy chắc chắn là lừa đảo, vì vậy hãy cẩn thận. ＞Nhờ có bạn mà mọi chuyện đều ổn.", "talkname0", 1);
Talk(33, "Không biết anh hùng trẻ tuổi có còn tin vào thỏa thuận tranh tài võ thuật trước đây không?", "talkname33", 0);
Talk(0, "＜Hóa ra tôi đang “suy nghĩ” về bốn điều đó của mình. >Đương nhiên là có tính, ta đã nói, chỉ cần trong thôn của ngươi có người có thể đánh bại ta, ta nhất định sẽ đưa cho ngươi bốn bức thư pháp và hội họa bằng cả hai tay.", "talkname0", 1);
Talk(33, "Đủ sảng khoái! Em trai. Chúng tôi, Zhuangshi, có một người bạn khác, nghe nói võ công của anh hùng trẻ tuổi rất tuyệt vời, anh ấy muốn tranh tài với bạn bất kể thế nào.", "talkname33", 0);
Talk(0, "Thế thôi, tốt! Không sao đâu, chỉ cần nhờ chủ thôn thứ hai giới thiệu tôi với bạn là được.", "talkname0", 1);
Talk(33, "Người bạn đó chưa bao giờ quen với cuộc sống dưới ánh mặt trời nên đã nhốt mình trong một hang động dưới Meizhuang.", "talkname33", 0);
Talk(0, "＜Trên thế giới này vẫn còn có những người thích nhốt mình trong hố, kỳ lạ thật. ＞", "talkname0", 1);
Talk(33, "Đây là chìa khóa, anh hùng trẻ tuổi, anh vào trước đi, tôi sẽ tìm ba anh em còn lại và kêu mọi người cùng nhau làm công chứng. Nhân tiện, lối vào hang nằm trong một căn phòng có bốn cái ghế và một cái bàn.", "talkname33", 0);
Talk(0, "Tại sao bốn bạn lại chơi mạt chược vào thời gian rảnh?", "talkname0", 1);
Talk(33, "Huh! Làm sao bạn biết? Đây là trò chơi mà bốn anh em tôi đang thực hiện. Hiện tại mới chỉ có nguyên mẫu, thậm chí ngay cả 4 cái tên của thẻ đặc biệt cũng chưa được quyết định?", "talkname33", 0);
Talk(0, "＜Có lẽ nào trò mạt chược này được bốn người này phát minh ra khi họ đang buồn chán? ＞Bạn muốn sử dụng tên gì?", "talkname0", 1);
Talk(33, "Chỉ cần sử dụng sở thích của bốn người chúng tôi là \"Tần, cờ, thư pháp và hội họa\".", "talkname33", 0);
Talk(0, "Không, dùng “xuân, hạ, thu đông” hay “mận, lan, trúc, cúc” sẽ tốt hơn. Nó có thể hiển thị tốt hơn những thay đổi của bốn mùa.", "talkname0", 1);
Talk(33, "Vâng? Nó có vẻ tốt.", "talkname33", 0);
Talk(0, "Tôi sẽ đi tìm anh ấy ngay bây giờ.", "talkname0", 1);
ModifyEvent(-2, -2, -2, -2, 281, -1, -1, -2, -2, -2, -2, -2, -2);
SetScenceMap(-2, 1, 28, 30, 1832);
SetScenceMap(-2, 1, 29, 30, 0);
SetScenceMap(-2, 1, 30, 30, 1836);
jyx2_FixMapObject("梅庄里门打开",1);
AddItem(161, 1);
do return end;
