Talk(36, "Thế còn bạn, bạn đã cứu được bố tôi chưa?", "talkname36", 0);
Talk(0, "Đã quá muộn rồi! Khi ta tới Thanh Thành phái, ta... cha của ngươi đã bị sát hại dã man.", "talkname0", 1);
Talk(36, "Cái gì! ! ! Họ đã giết... đã giết cha tôi.", "talkname36", 0);
Talk(0, "Đúng.", "talkname0", 1);
Talk(36, "Vũ Thương Hải! ! Nếu không báo thù chuyện này, Lâm Bình ta sẽ còn tệ hơn cả dã thú!", "talkname36", 0);
Talk(0, "Anh Lin, xin gửi lời chia buồn của tôi.", "talkname0", 1);
Talk(36, "Gia đình Lin của tôi có ác cảm gì với anh ta?", "talkname36", 0);
Talk(0, "Trên thế giới có tin đồn rằng nó dường như dành cho một cuốn sách bí mật có tên "Cẩm nang kiếm ác".", "talkname0", 1);
Talk(36, "Nhưng gia đình tôi thực sự không có sách hướng dẫn sử dụng kiếm để xua đuổi tà ma. Bảy mươi hai chiêu kiếm tà ác này là do chính cha tôi dạy nên không có sách hướng dẫn sử dụng kiếm.", "talkname36", 0);
Talk(0, "Người trong giới võ lâm đồn đại kiếm pháp này cực kỳ lợi hại nên đã thu hút sự thèm muốn của Yu Canghai, một tên trộm già.", "talkname0", 1);
Talk(36, "Nếu kiếm pháp chống ác của nhà họ Lâm thực sự mạnh mẽ thì nhà họ Lâm của ta đã không có kết cục như ngày hôm nay.", "talkname36", 0);
Talk(0, "Nhưng tổ tiên của ngươi không phải đã đánh bại Thường Khánh Tử sao?", "talkname0", 1);
Talk(36, "Vâng, có lẽ tôi và bố tôi vẫn chưa hiểu hết, từ nay tôi sẽ học thật tốt môn kiếm thuật này và báo thù cho bố mẹ. Cảm ơn sự giúp đỡ của bạn, anh hùng trẻ tuổi, tôi, Lin Pingzhi, sau này nhất định sẽ báo đáp lòng tốt này.", "talkname36", 0);
Talk(0, "Nhân tiện, cha cậu đã để lại vài lời cuối cùng trước khi qua đời. Ông nói: “Những đồ vật trong hầm của ngôi nhà cổ ở ngõ Tương Dương, Phúc Châu đều là tài sản tổ tiên của nhà họ Lâm và phải được bảo quản cẩn thận. Tuy nhiên, ông cố của chúng tôi Yuantu Gong đã để lại di sản và con cháu của dòng dõi này. Lâm gia không được phép nhìn vào, nếu không sẽ gặp phiền toái vô tận."", "talkname0", 1);
ModifyEvent(-2, 2, -2, -2, -1, -1, 313, -2, -2, -2, -2, -2, -2);
ModifyEvent(-2, -2, -2, -2, 314, -1, -1, -2, -2, -2, -2, -2, -2);
SetOneMagic(36, 0, 60, 100);
NPCAddItem(36, 78, 1);
SetSexual(36, 2);
AddEthics(2);
do return end;
