Talk(0, "Em trai này, em bị sao vậy?", "talkname0", 1);
Talk(38, "Tôi...tôi...tôi chỉ nhớ mình đang ngồi trên tảng đá tập khí công, đột nhiên nửa người lạnh nửa nóng...", "talkname38", 0);
Talk(0, "Chẳng lẽ anh trai tôi bị muỗi đốt?", "talkname0", 1);
Talk(38, "Bác già đâu? Anh ấy nói muốn dạy tôi cách bắt chim sẻ, nhưng anh ấy không nói với tôi rằng sau khi luyện tập tôi sẽ cảm thấy nóng lạnh, điều đó thật đáng buồn.", "talkname38", 0);
Talk(0, "Khả năng bắt chim sẻ?", "talkname0", 1);
Talk(38, "Đúng! Đầu tiên, chú già dạy tôi luyện công phu trên tượng đất sét, sau này tôi thường xuyên bị ớn lạnh toàn thân, nhưng chú già nói rằng đây là dấu hiệu bình thường của việc tập luyện kung fu. Sau này chú già dạy tôi những phương pháp huấn luyện khác, nhưng càng buồn hơn, lúc thì lạnh toàn thân, lúc thì nóng không chịu nổi, luyện tập kỹ năng bắt chim sẻ này vất vả quá!", "talkname38", 0);
Talk(0, "Hóa ra Xiongtai đã phát điên khi luyện tập khí công!", "talkname0", 1);
Talk(38, "Ah! Lại bắt đầu nữa...Tôi...Tôi sẽ không nói với bạn nữa.", "talkname38", 0);
ModifyEvent(-2, -2, -2, -2, 334, 335, -2, -2, -2, -2, -2, -2, -2);
do return end;
