ScenceFromTo(28, 24, 28, 17);
jyx2_CameraFollow("Level/NPC/baiwanjian");
Talk(41, "Các sứ giả của đảo Xiake, thưởng thiện và trừng phạt ác, đến gặp thủ lĩnh của Snow Mountain Sect!", "talkname41", 0);
Talk(43, "Hai người có phải là sứ giả của đảo Xiake, thưởng thiện phạt ác không?", "talkname43", 0);
Talk(42, "Chính xác. Không biết người đứng đầu Tuyết Sơn Giáo là ai? Theo lệnh của chủ nhân đảo Xiake, chúng tôi đến đây cầm huy chương đồng để mời thủ lĩnh giáo phái của bạn đến đảo của chúng tôi để trò chuyện và uống một bát cháo Laba.", "talkname42", 0);
ScenceFromTo(28, 17, 28, 24);
jyx2_CameraFollowPlayer();
Talk(0, "＜Có lẽ có manh mối trên đảo Xiake? Không có cuốn sách nào liên quan đến từ \"xia\" sao? ＞", "talkname0", 1);
WalkFromTo(28, 24, 28, 19);
jyx2_WalkFromTo(-1,2819);
Talk(0, "Bạn có thể cho tôi huy chương đồng được không?", "talkname0", 1);
Talk(41, "Tôi e là không, đảo Xiake mời là những người đứng đầu các giáo phái và các cao thủ võ thuật có hiểu biết đặc biệt về võ thuật.", "talkname41", 0);
Talk(0, "Vậy nếu tôi đánh bại anh ta, điều đó có nghĩa là tôi có tư cách hơn anh ta?", "talkname0", 1);
Talk(43, "Đứa nhỏ này ở đâu dám chạy lung tung trong thành Lăng Tiêu của chúng ta?", "talkname43", 0);
if TryBattle(59) == true then goto label0 end;
    Dead();
    do return end;
::label0::
    LightScence();
    Talk(0, "Tiền bối, tôi chấp nhận!", "talkname0", 1);
    Talk(43, "khịt mũi! Bai không còn gì để nói và không xấu hổ khi uống cháo Laba.", "talkname43", 0);
    Talk(41, "Tốt! Anh em hãy đến đảo Xiake ăn một bát cháo Laba vào ngày 8 tháng 12.", "talkname41", 0);
    DarkScence();
    jyx2_ReplaceSceneObject("", "NPC/shizhe1", "");--使者离开
    jyx2_ReplaceSceneObject("", "NPC/shizhe2", "");--使者离开
    ModifyEvent(-2, 12, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
    ModifyEvent(-2, 13, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
    ModifyEvent(-2, 10, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
    ModifyEvent(-2, 11, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
    ModifyEvent(-2, 5, -2, -2, 340, -1, -1, -2, -2, -2, -2, -2, -2);
    ModifyEvent(-2, 6, -2, -2, 340, -1, -1, -2, -2, -2, -2, -2, -2);
    ModifyEvent(-2, 7, -2, -2, 340, -1, -1, -2, -2, -2, -2, -2, -2);
    ModifyEvent(-2, 8, -2, -2, 340, -1, -1, -2, -2, -2, -2, -2, -2);
    ModifyEvent(-2, 9, -2, -2, 341, 342, -1, -2, -2, -2, -2, -2, -2);
    LightScence();
    AddItem(132, 1);
    AddEthics(1);
    AddRepute(2);
    ChangeMMapMusic(3);
do return end;
