Talk(39, "Anh Hemu của tôi đang ở trên một hòn đảo hoang ở một nơi xa xôi, tôi cảm thấy rất vinh dự khi được gặp Gao Xian ngày hôm nay. Chỉ là trên hoang đảo mọi thứ đều đơn giản, lòng hiếu khách cũng không trọn vẹn. Xin hãy tha thứ cho tôi.", "talkname39", 0);
Talk(40, "Thiếu gia từ xa đến nhưng hòn đảo của chúng tôi không hề tôn trọng ngài. Bát cháo Laba này ở ngoài không dễ uống, nhưng quan trọng nhất là “cỏ hại tim, hại xương, hại tim”, sau khi nở hoa mới có thể dùng được. Nhưng loài cỏ này mười năm mới nở hoa một lần. Chúng tôi luôn phải đợi đến khi hoa nở rồi mới mời các đồng tu đến thưởng thức, đây là lần thứ ba chúng tôi mời. Làm ơn, làm ơn, không có gì.", "talkname40", 0);
Talk(0, "Trong đầu tôi có một thắc mắc muốn nhờ các tiền bối cho lời khuyên?", "talkname0", 1);
Talk(39, "Nhưng nó không thành vấn đề.", "talkname39", 0);
Talk(0, "Tôi không biết tại sao hai chủ sở hữu hòn đảo lại phải mất nhiều công sức như vậy để triệu tập tất cả những người đứng đầu và giết họ.", "talkname0", 1);
Talk(39, "Thiếu gia, ngươi nói sai rồi! Làm sao bạn có thể tin được những lời đồn thổi trên đường?", "talkname39", 0);
Talk(0, "Theo chủ đảo, không có võ sư nào chết?", "talkname0", 1);
Talk(40, "Tất cả phàm nhân đều có số ngày nhất định để sống, khi đến thời hạn, nếu không phải là Lạc Cẩm Tiên thì làm sao có thể sống sót mà không chết? Không có ai bị giết trên đảo Xia Ke.", "talkname40", 0);
Talk(0, "Vậy tại sao những người này lại biến mất?", "talkname0", 1);
Talk(39, "Hãy để chúng tôi giải thích vấn đề này từ từ. Khoảng ba mươi năm trước, ta và Mục sư huynh kết bạn, cùng một tâm tư, vốn là muốn hợp lực trong giới võ lâm thưởng thiện phạt ác, làm tốt việc tốt trong giới võ lâm. Không ngờ vừa rời khỏi đấu trường, anh đã phát hiện ra một tấm bản đồ. Từ những dòng chữ nhỏ viết bên cạnh bức tranh, tôi biết được rằng có một bí mật kinh thiên động địa được ẩn giấu trên hoang đảo không tên trong bức tranh.", "talkname39", 0);
Talk(0, "Hòn đảo sa mạc không tên đó chắc chắn là Đảo Hiệp sĩ này.", "talkname0", 1);
Talk(39, "Thiếu gia nói đúng. Hòn đảo hoang không tên trên bản đồ chính là Đảo Hiệp sĩ ngay trước mặt bạn. Như trong hình, chúng tôi tìm kiếm trên đảo suốt mười tám ngày và cuối cùng đã tìm ra bí quyết võ học. Hóa ra đó là hình ảnh minh họa của một bài thơ cổ, ý nghĩa của nó vô cùng sâu sắc và phức tạp. Hai chúng tôi vui mừng khôn xiết và bắt đầu tập luyện theo sơ đồ. Nhưng sau vài tháng tập luyện, chúng tôi bỗng nảy sinh bất đồng quan điểm về các môn võ được thể hiện trong các bức tranh minh họa. Tôi nói rằng chúng ta nên thực hành như thế này, nhưng Anh Mu nói rằng tôi đã có ý kiến sai lầm và chúng ta phải thực hành như vậy. Có lẽ trình độ của tôi quá kém, kỹ thuật trong sơ đồ quá sâu sắc, dù đã nghiên cứu mấy tháng nhưng tôi vẫn không thể hiểu được. Sau đó, anh Mu và tôi đã thảo luận chi tiết về vấn đề này, dường như nếu muốn hiểu được toàn cảnh thì phải tập hợp trí tuệ của mình lại. Tục ngữ có câu: Ba người thợ giày xứng đáng với Gia Cát Lượng. Tại sao chúng ta không mời tất cả những con người tài năng từ khắp nơi trên thế giới đến đảo và cùng nhau nỗ lực hết mình để nghiên cứu. Vào thời điểm đó trên đảo đã nở hoa “Thảo mộc Tâm tiêu xương”, nếu loại thảo mộc này kết hợp với các loại thảo mộc khác và nấu thành cháo nóng sẽ có lợi ích rất lớn cho người luyện võ chúng ta. Vì vậy, hai chúng tôi đã cử sứ giả mời những người đứng đầu các giáo phái nổi tiếng, các nhà lãnh đạo của các tôn giáo khác nhau và các nhà lãnh đạo của các băng đảng khác nhau đến đảo của chúng tôi để ăn một bát cháo Laba. Uống cháo xong bảo các em nghiên cứu tranh minh họa.", "talkname39", 0);
Talk(0, "Trong trường hợp này, bạn đang làm điều đó vì lòng tốt bằng cách mời mọi người đến uống cháo Laba.", "talkname0", 1);
Talk(39, "Đúng. Và chúng tôi không cấm bất cứ ai rời đi, nhưng mỗi võ sĩ đều bị ám ảnh bởi việc nghiên cứu minh họa này. Nhưng đáng tiếc là mọi người vẫn chưa hiểu hết được hình ảnh minh họa của bài thơ cổ này. Tốt! Dù chúng ta đã đưa đến đây nhiều hiền nhân thông thạo thơ ca nhưng vẫn không thể giải đáp được bí ẩn của bài thơ cổ này. Bây giờ xin mời vị anh hùng trẻ tuổi vào hang nghiên cứu, có lẽ ông trời sẽ phù hộ cho việc giải mã bài thơ này và nó sẽ rơi vào người anh hùng trẻ tuổi. Nếu anh hùng trẻ tuổi muốn rời đi, anh ta có thể tự mình rời đi.", "talkname39", 0);
AddItem(32, 1);
ModifyEvent(-2, 2, -2, -2, 381, -1, -1, -2, -2, -2, -2, -2, -2);
ModifyEvent(-2, 3, -2, -2, 382, -1, -1, -2, -2, -2, -2, -2, -2);
ModifyEvent(-2, 0, -2, -2, 368, -1, -1, -2, -2, -2, -2, -2, -2);
ModifyEvent(-2, 1, -2, -2, 369, -1, -1, -2, -2, -2, -2, -2, -2);
ModifyEvent(-2, 16, 0, 0, -1, -1, 371, -2, -2, -2, -2, -2, -2);
Add3EventNum(-2, 4, 0, 0, 1);
Add3EventNum(-2, 5, 0, 0, 1);
Add3EventNum(-2, 6, 0, 0, 1);
do return end;
