if InTeam(38) == true then goto label0 end;
    do return end;
::label0::
-- DarkScence()
-- jyx2_ReplaceSceneObject("", "NPC/shipotian4", "1");--石破天出现
-- LightScence()
    Talk(38, "Anh à, ở đây chẳng có gì để xem cả. Chúng ta đi thôi nhé?", "talkname38", 1);
    Talk(0, "Anh em thân mến, xin hãy nhỏ giọng và đừng làm phiền hai chủ đảo luyện tập...", "talkname0", 1);
    Talk(38, "＜Tại sao những từ này lại kỳ lạ đến mức chỉ cần nhìn thôi cũng khiến bạn choáng váng? ＞＜Điểm Zhiyang nóng quá, hóa ra những con nòng nọc này tưởng chừng như đang bơi lội ngẫu nhiên nhưng thực ra có liên quan đến hơi thở bên trong＞", "talkname38", 1);
    Talk(39, "Anh Shi này đã để mắt đến "Kinh Thái Huyền", hóa ra anh ta là một học giả hào phóng, thông thạo văn xuôi nòng nọc.", "talkname39", 0);
    Talk(38, "Người đàn ông nhỏ bé không biết một chữ, nhưng nhìn những con nòng nọc nhỏ này rất thú vị nên anh ta quan sát chúng một lúc.", "talkname38", 1);
    Talk(39, "Chính là nó, "Kinh Thái Huyền" này được viết bằng chữ cổ Nòng Nọc, không ngờ Thạch sư huynh tuổi còn trẻ như vậy lại có thiên tài như vậy, lại có thể đọc được chữ cổ như vậy.", "talkname39", 0);
    Talk(38, "＜Tốt nhất tôi không nên làm phiền hai chủ hòn đảo...nhưng con nòng nọc này vui thật đấy...＞＜Này! Tại sao những con nòng nọc này lại chạy khắp người tôi... Tại sao tôi lại cảm thấy thoải mái đến thế...>", "talkname38", 1);
    Talk(0, "Anh trai thân mến, anh đang làm gì vậy?", "talkname0", 1);
    DarkScence();
    LightScence();
    Talk(38, "Ah! Quá mệt mỏi. Tại sao tôi lại cảm thấy mệt mỏi thế này?", "talkname38", 1);
    Talk(0, "Anh thân mến, cuối cùng anh cũng đã tỉnh dậy.", "talkname0", 1);
    Talk(38, "Cái gì, tôi đã ngất đi à?", "talkname38", 1);
    Talk(0, "Đúng! Lúc đầu ta còn tưởng ngươi lại bị ma quỷ nhập vào, nhưng sau đó Long Đảo chủ nói ngươi đang thức tỉnh thần thông nên ta cũng không quấy rầy ngươi, từ đó đến nay đã ba ngày rồi.", "talkname0", 1);
    Talk(38, "Vâng? Đã ba ngày rồi, chẳng trách tôi lại đói đến thế.", "talkname38", 1);
    Talk(0, "Anh thân mến, cuối cùng anh cũng đã tỉnh dậy.", "talkname0", 1);
    Talk(39, "Anh Shi, bí ẩn lớn mà anh em em ấp ủ trong lòng mấy chục năm cuối cùng cũng đã được giải đáp, em vô cùng biết ơn anh.", "talkname39", 0);
    Talk(38, "Làm sao... làm sao tôi bẻ được nó?", "talkname38", 1);
    Talk(39, "Tại sao Anh Shi phải khiêm tốn như vậy? Bạn đã hiểu rõ bản đồ tường đá của "Hạ Khả Hành" này, không chỉ bạn là người đầu tiên trong giới võ lâm ngày nay, ngoại trừ tiền bối khắc bản đồ trên tường đá, e rằng sẽ có rất ít người có thể phù hợp với bạn ở mọi lứa tuổi.", "talkname39", 0);
    Talk(38, "Kẻ ác không dám, kẻ ác không dám.", "talkname38", 1);
    Talk(39, "Tôi và Mục sư huynh có hiểu biết chưa đến 10% về dòng chữ cổ của con nòng nọc trên tường đá, không biết Thạch sư huynh có chịu cho tôi một lời khuyên không?", "talkname39", 0);
    Talk(38, "Tôi đã nói với các bạn rồi, khi tôi nhìn con nòng nọc này thì "điểm Zhongzhu" nhảy lên, khi tôi nhìn con nòng nọc này lần nữa thì "điểm Thái Hà" nhảy lên rất to...", "talkname38", 1);
    Talk(39, "Thì ra... hóa ra... Thạch bang chủ nhìn từng dòng... con nòng nọc đó, không phải từng chữ... Vậy làm sao Thạch bang chủ có thể hiểu được toàn bộ "Thái Huyền kinh"?", "talkname39", 0);
    Talk(38, "Nhân vật phản diện từ nhỏ đến nay chưa từng đọc sách, hắn thật sự không biết một chữ, rất xấu hổ.", "talkname38", 1);
    Talk(40, "Bạn không thể đọc?", "talkname40", 0);
    Talk(38, "mù chữ. Tôi... sau khi về nhất định phải học đọc, nếu không thì mọi người đều có thể đọc được còn tôi thì không, người ta cười nhạo tôi sẽ xấu hổ lắm.", "talkname38", 1);
    Talk(39, "Bạn không biết chữ, vậy ai đã giải nghĩa nhiều dòng chữ trên tường cho bạn?", "talkname39", 0);
    Talk(38, "Không ai giải thích cho tôi. Tôi... đang nhìn đồ họa và suy nghĩ lung tung thì đột nhiên, những đám mây hay những thanh kiếm nhỏ trên tranh liên hệ với hơi nóng trong cơ thể tôi.", "talkname38", 1);
    Talk(40, "Bạn không biết chữ, nhưng bạn có thể giải mã được tập bản đồ. Làm sao điều này có thể xảy ra?", "talkname40", 0);
    Talk(39, "Có thực sự có ý muốn của Thiên Chúa trong bóng tối? Anh Shi này thực sự rất tài năng.", "talkname39", 0);
    Talk(40, "...Tôi hiểu, tôi hiểu. Thưa anh, thế thôi.", "talkname40", 0);
    Talk(40, "Ah! Đúng. Đúng. Anh Shi, nhờ mù chữ nên anh phải giải được bí ẩn lớn này. Tốt! Hóa ra mỗi lời bình luận trong số rất nhiều bài bình luận này đều khiến mọi người lạc lối. Nhưng ai trong số những người nghiên cứu tập bản đồ lại không đi sâu vào các chú thích.", "talkname40", 0);
    Talk(39, "Thì ra “Tai Huyền Kinh” này thực chất không phải là bài viết của con nòng nọc, nó chỉ là… chỉ là phương hướng của một số kinh mạch và huyệt đạo mà thôi. Than ôi, ba mươi năm, ba mươi năm!", "talkname39", 0);
    Talk(40, "Bạch Thủ Thái Huyền Cảnh! Anh ơi, tóc anh bạc trắng quá.", "talkname40", 0);
    Talk(39, "Khi đó ông Jin cũng khuyên chúng tôi không nên đào sâu quá vào tấm bản đồ này mà hãy xử lý nó bằng tâm trí bình thường, lúc đó làm sao mà nghe được?", "talkname39", 0);
    Talk(0, "Bạn đã gặp Jin tiền bối chưa?", "talkname0", 1);
    Talk(39, "Đúng! Khi còn trẻ, chúng tôi đã gặp nhau một lần khi lần đầu tiên có được tấm bản đồ này.", "talkname39", 0);
    Talk(0, "Bạn có biết mười bốn cuốn sách đó ở đâu không?", "talkname0", 1);
    Talk(39, "Tôi không biết gì khác, nhưng cuốn sách "Xia Ke Xing" có cùng tên với hòn đảo này hiện đang thuộc quyền sở hữu của tôi. Bởi vì tôi nghĩ nó có thể liên quan đến tấm bản đồ này nên tôi đã lấy nó ra. Nhưng sau này đọc lại tôi không hiểu và không biết viết gì.", "talkname39", 0);
    Talk(0, "Vậy thì cuốn sách này...", "talkname0", 1);
    Talk(39, "Bây giờ bí ẩn của tập bản đồ đã được giải đáp, Thái Huyền Ma Pháp Công đã được Thạch sư huynh nắm giữ, cuốn sách này đối với chúng ta không có ý nghĩa gì. Nếu bạn muốn nó, hãy lấy nó.", "talkname39", 0);
    Talk(0, "Cảm ơn Long Đảo Chủ, chuyện này đối với ta mà nói rất quan trọng. Anh thân mến, lần này anh đã lập được một kỳ công lớn.", "talkname0", 1);
    Talk(38, "Người mù chữ có lợi ích gì không?", "talkname38", 1);
    Talk(39, "Anh à, anh và em đã hoàn thành tâm nguyện rồi, đã đến lúc chúng ta nên nghỉ ngơi. Cuộc hẹn với món cháo Laba này sẽ không còn cần thiết nữa. Chúng tôi sẽ thông báo với các nhà lãnh đạo rằng các bạn không cần nghiên cứu sơ đồ này nữa. Thiếu gia, ngài có thể nhanh chóng rời đi, nhưng đừng nói cho ai biết rằng Thạch ca đã nắm giữ thần thông này, nếu không sẽ gặp phiền toái vô tận.", "talkname39", 0);
    Talk(0, "Tiền bối, tạm biệt.", "talkname0", 1);
    DarkScence()
    AddItem(154, 1);
    AddItem(60, 1);
    ModifyEvent(-2, 0, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
    ModifyEvent(-2, 1, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
    ModifyEvent(-2, 7, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
    ModifyEvent(-2, 8, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
    ModifyEvent(-2, 9, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
    ModifyEvent(-2, 10, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
    ModifyEvent(-2, 11, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
	jyx2_ReplaceSceneObject("", "NPC/唐文亮7", "");
	jyx2_ReplaceSceneObject("", "NPC/何太冲8", "");
	jyx2_ReplaceSceneObject("", "NPC/定闲9", "");
	jyx2_ReplaceSceneObject("", "NPC/天门道人10", "");
	jyx2_ReplaceSceneObject("", "NPC/莫大11", "");
    ModifyEvent(-2, 12, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
    ModifyEvent(-2, 13, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
	jyx2_FixMapObject("侠客岛岛主移动到房间",0);
	jyx2_SwitchRoleAnimation("NPC/龙岛主","Assets/BuildSource/AnimationControllers/NanxianController.controller");
	jyx2_SwitchRoleAnimation("NPC/木岛主","Assets/BuildSource/AnimationControllers/NanxianController.controller");
    ModifyEvent(-2, 16, 0, 0, -1, -1, 388, -1, -1, -1, -2, -2, -2);
    ModifyEvent(-2, 17, 0, 0, -1, -1, 388, -1, -1, -1, -2, -2, -2);
    ModifyEvent(-2, 18, 0, 0, -1, -1, 388, -1, -1, -1, -2, -2, -2);
    ModifyEvent(-2, 2, 1, 1, 364, -1, -1, 5132, 5132, 5132, -2, -2, -2);
    ModifyEvent(-2, 3, 1, 1, 365, -1, -1, 5136, 5136, 5136, -2, -2, -2);
    ModifyEvent(-2, 14, 1, 1, 366, -1, -1, 5148, 5148, 5148, -2, -2, -2);
    ModifyEvent(-2, 15, 1, 1, 367, -1, -1, 5142, 5142, 5142, -2, -2, -2); 
	jyx2_FixMapObject("侠客岛弟子移动到岛主后",1);
    LightScence();
    LearnMagic2(38, 23, 0);
    AddAttack(38, 10);
    ModifyEvent(39, 9, 0, 0, 345, -1, -1, -1, -1, -1, -2, -2, -2);
do return end;
