if HaveItem(173) == false then goto label0 end;
    ModifyEvent(-2, -2, -2, -2, -1, -1, -1, -2, -2, -2, -2, -2, -2);
    do return end;
::label0::
    Talk(0, "Sao mùi thơm quá, đầu óc choáng váng quá, a! Những cây ngập mặn này có độc không?", "talkname0", 1);
    jyx2_PlayTimeline("[Timeline]ka37_药王山庄_晕倒", 0, false);
    jyx2_Wait(2);
    PlayAnimation(-1, 5974, 5992);
    DarkScence();
    jyx2_StopTimeline("[Timeline]ka37_药王山庄_晕倒");
    SetScencePosition2(30, 49);
	jyx2_MovePlayer("passout", "Level/Dynamic");
    jyx2_PlayTimeline("[Timeline]ka37_药王山庄_苏醒", 0, false);
    LightScence();
    jyx2_Wait(1.2);
    PlayAnimation(-1, 6014, 6024);
    Talk(0, "Huh! Đây là đâu? Chẳng lẽ tôi đã bất tỉnh từ lâu rồi sao? Đây không phải là nơi bình thường.", "talkname0", 1);
    jyx2_StopTimeline("[Timeline]ka37_药王山庄_苏醒");
    ModifyEvent(-2, -2, -2, -2, -2, -2, 38, -2, -2, -2, -2, -2, -2);
do return end;
