if HaveItem(173) == false then goto label0 end;
    ModifyEvent(-2, -2, -2, -2, -1, -1, -1, -2, -2, -2, -2, -2, -2);
    Talk(0, "Huh! Đầu óc tôi đỡ choáng váng hơn, nhưng lại có mùi thơm thoang thoảng, bông hoa màu xanh này thực sự rất thần kỳ.", "talkname0", 1);
    do return end;
::label0::
    Talk(0, "Ah! Tôi lại ngửi thấy mùi thơm này và có vẻ như tôi sắp ngất đi lần nữa.", "talkname0", 1);
    jyx2_PlayTimeline("[Timeline]ka37_药王山庄_晕倒", 0, false);
    jyx2_Wait(2);
    PlayAnimation(-1, 5974, 5992);
    DarkScence();
    jyx2_StopTimeline("[Timeline]ka37_药王山庄_晕倒");
    SetScencePosition2(30, 49);
	jyx2_MovePlayer("passout", "Level/Dynamic");
    jyx2_PlayTimeline("[Timeline]ka37_药王山庄_苏醒", 0, false);
    LightScence();
    jyx2_Wait(1.2);
    PlayAnimation(-1, 6014, 6024);
    Talk(0, "Tôi lại ngất đi, có vẻ như tôi phải nghĩ ra cách giải quyết.", "talkname0", 1);
    jyx2_StopTimeline("[Timeline]ka37_药王山庄_苏醒");
do return end;
