Talk(0, "Anh ơi, em không biết anh đã thuần hóa được con đại bàng lớn trong hang... Này! Cánh tay của bạn? Chẳng lẽ đại bàng lại làm như vậy... Than ôi! Tôi vừa mới cứu nó ra, nếu biết thì nó đã bị mãng xà khổng lồ cắn chết rồi.", "talkname0", 1);
Talk(58, "Trăn? Bạn nói bạn đã cứu Diao Brother, Yang Guo xin cảm ơn bạn.", "talkname58", 0);
Talk(0, "Vết thương của bạn không phải do con đại bàng gây ra sao?", "talkname0", 1);
Talk(58, "KHÔNG.", "talkname58", 0);
Talk(0, "Nhưng xem ra ngươi gần đây giống như bị thương, không biết Dương ca gặp phải khó khăn gì, ngươi có muốn giúp ta không?", "talkname0", 1);
Talk(58, "Vết thương này? Tốt! Không nhắc tới thì thế nào?", "talkname58", 0);
Talk(0, "Có thể là một người phụ nữ?", "talkname0", 1);
Talk(58, "Làm sao bạn biết?", "talkname58", 0);
Talk(0, "Tôi chỉ đoán bừa thôi, vì từ xa xưa chỉ có con điếm mới biến thái đến mức chặt đứt tay người ta.", "talkname0", 1);
Talk(58, "Tốt! Chúng ta đừng nói về chuyện này nữa. Tôi tự hỏi tại sao người anh hùng trẻ tuổi lại ở đây?", "talkname58", 0);
Talk(0, "Thành thật mà nói, tôi đang tìm kiếm thứ gì đó, và tất nhiên tôi phải đến một nơi bí mật để tìm thứ gì đó. Sau khi tìm kiếm, tôi đã đến được thung lũng này. Vừa vào hang, họ đã nhìn thấy một con đại bàng khổng lồ và một con mãng xà khổng lồ đang đánh nhau. Con đại bàng lớn đó có phải do anh Dương nuôi không?", "talkname0", 1);
Talk(58, "KHÔNG. Thực ra tôi vô tình đến thung lũng này và phát hiện ra Anh Diao. Sau một thời gian quen nhau, chúng tôi đã trở thành bạn tốt của nhau. Theo những gì tôi nhìn thấy trong hang, con đại bàng này lẽ ra phải được nuôi dưỡng bởi một tiền bối tên là Dugu Qiubai.", "talkname58", 0);
Talk(0, "Một mình tìm kiếm sự thất bại?", "talkname0", 1);
Talk(58, "Đúng vậy, vị tiền bối này tự xưng là "Kiếm Quỷ Dugu tìm thất bại". Trong nét chữ ông để lại, ông viết: “Hơn ba mươi năm ở sông hồ, tôi đã giết hết kẻ thù và đánh bại tất cả các anh hùng. Thế giới không còn ai để chống cự. Tôi không còn cách nào khác là phải sống trong ẩn dật trong thung lũng sâu và có đại bàng làm bạn. Woohoo, tôi cầu nguyện cho bạn trong đời. Thật cô đơn và xấu hổ khi không có đối thủ trong tay. "Người đàn anh này không còn lựa chọn nào khác ngoài việc sống ẩn dật trên núi vì anh ta là bất khả chiến bại trên thế giới. Kỹ năng võ thuật của anh ấy sâu sắc đến mức tôi thực sự không biết anh ấy đã cao cấp đến mức nào. Người này được mệnh danh là "Quỷ kiếm", anh ta là một vị thần có kiếm thuật và tên là "Qiufei", anh ta nghĩ rằng anh ta đã đi khắp thế giới để tìm người có thể đánh bại anh ta, nhưng anh ta không bao giờ có thể làm được. , và cuối cùng chết ở đây trong cơn trầm cảm. Mỗi khi nhớ lại ân đức của người tiền nhiệm, tôi không khỏi... khụ khụ... khụ khụ... tôi không khỏi khao khát nó... khụ khụ... khi bắt đầu nói tôi nói quá nhiều .", "talkname58", 0);
Talk(0, "Anh Dương hình như bị thương?", "talkname0", 1);
Talk(58, "Thành thật mà nói, anh hùng trẻ tuổi Yang bị "bông hoa tình yêu" đầu độc và có thể không tồn tại được lâu.", "talkname58", 0);
Talk(0, "Dương sư huynh, ngươi đang nói cái gì vậy, ca ca, ta giúp ngươi tìm một vị danh y đến xem, trên đời không có bệnh nào là không thể chữa khỏi.", "talkname0", 1);
Talk(58, "Anh hùng trẻ tuổi không cần lo lắng, loài hoa tình yêu này chỉ có ở Thung lũng Tuyệt Thanh, độc tính của nó chỉ có thể chữa khỏi bằng "Thuốc Tuyệt Thanh".", "talkname58", 0);
Talk(0, "Sau đó ta sẽ đi đến Thung lũng Vô tâm cho anh trai mình và tìm Viên thuốc Vô tâm này.", "talkname0", 1);
Talk(58, "Bây giờ Thung lũng Tuyệt Thanh hẳn đã bị bỏ hoang, và tôi cũng đã ném Viên thuốc Tuyệt Thanh cuối cùng xuống đáy Thung lũng Tuyệt Thanh... Vì vậy, vì vậy... Vì vậy, vì vậy... Long'er rời đi với Nanhai Shenni, và tôi không không biết anh ấy thế nào rồi... …ah! ...Tôi...tôi nhớ cô ấy rất nhiều...", "talkname58", 0);
Talk(0, "Thì ra là chuyện như thế này, tôi nghĩ tốt nhất là nên cầu xin Dương huynh tạm thời kìm nén dục vọng, kẻo khơi dậy chất độc tình yêu. Tôi vẫn đi khắp nơi tìm kiếm các bác sĩ nổi tiếng để xem có cách nào khác để chữa khỏi loại độc hoa tình yêu này không. Nếu không, mười sáu năm sau, cô Long sẽ không thể gặp Dương ca khi cô khỏi bệnh trở về.", "talkname0", 1);
Talk(58, "Nếu Dương không bị trúng độc nặng thì đã đi theo anh hùng trẻ tuổi.", "talkname58", 0);
Talk(0, "Có vẻ như trước tiên tôi phải đi một chuyến đến Thung lũng Tuyệt Thanh để xem “bông hoa tình yêu” này trông như thế nào. Có lẽ sẽ có thứ gì đó được thu hoạch trong thung lũng. Người ta thường nói, ở đâu có rắn độc thì phải có thuốc giải trong vòng bảy bước.", "talkname0", 1);
Talk(58, "Người anh hùng trẻ tuổi phải cẩn thận để không bị bông hoa tình yêu đó đốt, nếu không...", "talkname58", 0);
Talk(0, "Nếu không, trên đời sẽ còn có một người nữa phải chịu “nỗi đau khổ” giống như anh Dương. Bây giờ tôi đi đây, anh Yang hãy bảo trọng nhé.", "talkname0", 1);
Talk(58, "Nhân tiện, Thung lũng Jueqing nằm ở một nơi xa xôi, bạn phải đi thuyền ngược sông Hoàng Hà để đến đó.", "talkname58", 0);
ModifyEvent(-2, -2, -2, -2, 395, 396, -1, -2, -2, -2, -2, -2, -2);
ModifyEvent(-2, 7, -2, -2, -1, -1, 398, -2, -2, -2, -2, -2, -2);
ModifyEvent(-2, 8, -2, -2, -1, -1, 398, -2, -2, -2, -2, -2, -2);
ModifyEvent(-2, 9, -2, -2, -1, -1, 398, -2, -2, -2, -2, -2, -2);
ChangeMMapMusic(3);
do return end;
