Talk(0, "Cô gái, đây có phải là Diệu Vương Trang không? ＜Có lẽ nào cô ấy là vua thuốc độc? ＞", "talkname0", 1);
Talk(2, "Tại sao bạn lại đến Yaowangzhuang?", "talkname2", 0);
Talk(0, "Phật mặt vàng Miao Daxia bị đầu độc và bị thương, chất độc được sử dụng là do kẻ phản bội lấy trộm từ người tiền nhiệm, ông hy vọng rằng người tiền nhiệm sẽ từ bi và đưa cho ông thuốc giải độc.", "talkname0", 1);
Talk(2, "khịt mũi! Giang sư huynh tùy ý đưa thuốc độc cho người ngoài, người thế gian lại đổ chuyện này cho Sư phụ. Lần này là loại chất độc gì?", "talkname2", 0);
Talk(0, "Hóa ra vua thuốc độc tay chính là sư phụ của ngươi, lại khiến tiền bối của ta gào thét như điên, ngươi không sợ rút ngắn tuổi thọ sao?", "talkname0", 1);
Talk(2, "Tôi không yêu cầu bạn sủa, bạn chỉ thích sủa thôi.", "talkname2", 0);
Talk(0, "Tôi cũng để cô gái mời Dược Vương tiền bối ra ngoài, tôi muốn xin hắn thuốc giải độc cho cỏ Đoạn Tâm.", "talkname0", 1);
Talk(2, "Thầy tôi đã qua đời.", "talkname2", 0);
Talk(0, "Vậy chúng ta nên làm gì?", "talkname0", 1);
Talk(2, "Chất độc của cỏ đau lòng không quá khó để giải độc.", "talkname2", 0);
Talk(0, "Hóa ra cô gái đã nhận được tiểu sử thật của Dược Vương tiên sinh, đồng thời ông cũng yêu cầu cô gái đưa thuốc giải độc cho mình.", "talkname0", 1);
Talk(2, "Tôi có thể cho bạn thuốc giải độc, miễn là bạn làm một việc cho tôi.", "talkname2", 0);
Talk(0, "Có chuyện gì vậy?", "talkname0", 1);
Talk(2, "Bạn có giỏi kung fu không?", "talkname2", 0);
Talk(0, "Tôi quyết tâm trở thành người đứng đầu liên minh võ thuật nên kỹ năng của tôi đương nhiên là tốt.", "talkname0", 1);
Talk(2, "Âm thanh khá lớn. Được rồi, tôi muốn bạn giúp tôi tìm một thứ.", "talkname2", 0);
Talk(0, "Gì?", "talkname0", 1);
Talk(2, "Thu Hải Đường Qixin. Vì thứ này đã bị anh trai Giang của tôi đánh cắp nên hiện tại tôi không biết nó ở đâu. Nếu không nhanh chóng tìm lại, không biết trên đầu Diệu Vương Trang sẽ ghi bao nhiêu nợ xấu.", "talkname2", 0);
Talk(0, "Vậy tôi nên tìm nó ở đâu?", "talkname0", 1);
Talk(2, "Nếu tôi biết, liệu tôi còn cần anh tìm tôi không? Nhưng bạn có thể chú ý hơn đến những người sử dụng chất độc, ma túy một cách bừa bãi để làm hại con người.", "talkname2", 0);
Talk(0, "Bạn vẫn chưa biết tên cô gái à?", "talkname0", 1);
Talk(2, "Trình Linh Túc.", "talkname2", 0);
Talk(0, "Vậy cô Ling xin nghỉ đi.", "talkname0", 1);
ModifyEvent(-2, -2, -2, -2, 40, 41, -2, -2, -2, -2, -2, -2, -2);
do return end;
