Talk(0, "Senior có lẽ là thủ lĩnh của Iron Palm Gang.", "talkname0", 1);
Talk(67, "Con trai! Bạn là ai!", "talkname67", 0);
Talk(0, "Thế hệ trẻ đi ngang qua chân núi Cọ Thiết, nhìn thấy hình dáng kỳ lạ của ngọn núi, liền lên núi nhìn xem, không ngờ người của các ngươi lại bắt đầu đánh người. Ngọn núi này có thuộc về bạn không?", "talkname0", 1);
Talk(67, "Một cậu bé không biết đến độ cao của thế giới. Bạn có biết ai có kỹ năng võ thuật cao nhất thế giới?", "talkname67", 0);
Talk(0, "Tôi từng nghe ai đó nói rằng Dongxie, Xidu, Nandi và Beibei là bốn người có võ thuật mạnh nhất thế giới.", "talkname0", 1);
Talk(67, "Khi diễn ra cuộc tranh luận về kiếm thuật ở Hoa Sơn, nếu tôi chưa thành thạo kỹ năng cọ sắt, tôi sẽ không có thời gian để tham gia. Bằng không, làm sao danh hiệu “Võ sư giỏi nhất thế giới” lại có thể bị Vương Trùng Dương tước đi. Bây giờ kỹ năng ma thuật của tôi đã hoàn thiện, trong Cuộc thảo luận về kiếm thuật Huashan tiếp theo, tôi sẽ cho thế giới biết ai là người có kỹ năng võ thuật cao nhất thế giới hiện nay.", "talkname67", 0);
Talk(0, "Vâng? Nhưng tôi cũng sẽ tham gia đại hội này, tôi cũng muốn có được danh hiệu võ thuật giỏi nhất thế giới.", "talkname0", 1);
Talk(67, "Có phải tất cả giới trẻ ngày nay đều kiêu ngạo như bạn không? Hôm nay tôi sẽ cho em nếm trải nỗi đau.", "talkname67", 0);
if TryBattle(71) == true then goto label0 end;
    Dead();
    do return end;
::label0::
    ModifyEvent(-2, -2, -2, -2, 451, -1, -1, -2, -2, -2, -2, -2, -2);
    ModifyEvent(-2, 16, -2, -2, 474, -1, -1, -2, -2, -2, -2, -2, -2);
    ModifyEvent(-2, 17, -2, -2, 474, -1, -1, -2, -2, -2, -2, -2, -2);
    ModifyEvent(-2, 18, -2, -2, 474, -1, -1, -2, -2, -2, -2, -2, -2);
    LightScence();
    Talk(0, "Lão già, ta nghĩ ngươi tốt nhất không nên tham gia vào cuộc tranh luận kiếm Hoa Sơn tiếp theo mà tiếp tục chăm chỉ luyện tập.", "talkname0", 1);
    AddRepute(5);
do return end;
