Talk(90, "Hiện tại hai sứ giả thưởng thiện phạt ác đang đi tuần tra, trên thế giới không băng đảng hay giáo phái nào có thể tự do...", "talkname90", 0);
Talk(90, "Lão Lý, lỡ như chú của sư phụ được lệnh rời đi thì sao?", "talkname90", 4);
Talk(90, "Không có sự trở lại. Trong số các thủ lĩnh băng đảng, thủ lĩnh và thủ lĩnh được lệnh đến đảo Xiake trong ba mươi năm qua... có ai trong số họ quay trở lại không?", "talkname90", 0);
Talk(0, "Vậy đảo Hạ Khắc ở đâu? Tại sao tất cả các nhà lãnh đạo đều ra đi và không bao giờ quay trở lại?", "talkname0", 1);
Talk(90, "Này chàng trai, đừng nghe lén người khác nói gì.", "talkname90", 0);
Talk(0, "Tôi đã nói rất to...", "talkname0", 1);
ModifyEvent(-2, 2, -2, -2, 479, -2, -2, -2, -2, -2, -2, -2, -2);
ModifyEvent(-2, 6, -2, -2, 479, -2, -2, -2, -2, -2, -2, -2, -2);
ModifyEvent(-2, 7, -2, -2, 479, -2, -2, -2, -2, -2, -2, -2, -2);
do return end;
