Talk(0, "Người phụ nữ trong bức tượng này khá xinh đẹp... Ơ! Phía dưới viết mấy chữ... "Cúi lạy một ngàn lần, để ta dắt ngươi, tuân theo mệnh lệnh của ta, không bao giờ hối hận"... <Điên muốn lạy tượng đá>", "talkname0", 1);
if InTeam(53) == true then goto label0 end;
    do return end;
::label0::
    jyx2_ReplaceSceneObject("", "NPC/段誉11", "1");--段誉出现
    Talk(53, "Em gái thần tiên của tôi, Xiaosheng Duan Yu, hôm nay có thể nhìn thấy khuôn mặt xinh đẹp của cô ấy và chết mà không hối tiếc. Chị tôi chết và sống một mình ở đây có phải là quá cô đơn không?", "talkname53", 1);
    Talk(0, "Anh Duẩn, anh đang nói chuyện với bức tượng ngọc này phải không? ＜Người đàn ông này thực sự có năng lực＞", "talkname0", 1);
    Talk(53, "Trong núi Miaogushe, có một vị thần và một người đàn ông sống ở đó, làn da của anh ấy như băng và tuyết, và anh ấy duyên dáng như một trinh nữ, anh ấy không ăn ngũ cốc, nhưng thở gió và uống sương. Tiên nữ ơi, nếu em có thể sống và nói với anh một lời, anh sẽ chết vì em một ngàn lần, mười ngàn lần, giống như đạt được hạnh phúc tột cùng, niềm vui vô bờ bến. Cúi đầu ngàn lần là chuyện đương nhiên...", "talkname53", 1);
    DarkScence();
    ModifyEvent(-2, 0, -2, -2, -2, -2, -2, 6316, 6316, 6316, -2, -2, -2);
    jyx2_SwitchRoleAnimation("NPC/段誉11", "Assets/BuildSource/AnimationControllers/KneelController.controller");
	jyx2_MovePlayer("观看段誉磕头","Level/Dynamic");
    LightScence();
    PlayAnimation(0, 6316, 6334);
    PlayAnimation(0, 6316, 6334);
    jyx2_SwitchRoleAnimation("NPC/段誉11", "Assets/BuildSource/AnimationControllers/备份/DuanyuKneelController.controller");
    Talk(0, "Anh trai, anh đang làm gì vậy? Bạn thực sự phải gõ một ngàn lần!", "talkname0", 1);
    Talk(53, "Mười, mười một, mười hai...", "talkname53", 1);
    PlayAnimation(0, 6316, 6334);
    PlayAnimation(0, 6316, 6334);
    PlayAnimation(0, 6316, 6334);
    Talk(0, "Ôi chúa ơi!", "talkname0", 1);
    DarkScence();
    ModifyEvent(-2, 0, -2, -2, -2, -2, -2, 6338, 6338, 6338, -2, -2, -2);
	jyx2_ReplaceSceneObject("", "Dynamic/Chair_11", "");--需要替换破烂的蒲团
    ModifyEvent(-2, 11, -2, -2, -2, -2, -2, 6312, 6312, 6312, -2, -2, -2);
    jyx2_SwitchRoleAnimation("NPC/段誉11", "Assets/BuildSource/AnimationControllers/备份/DuanyuController.controller");
    LightScence();
    Talk(0, "Ca ca, ngươi thật là quỳ lạy ngàn lần, đầu ngươi không sao chứ? Bạn thấy đấy, tấm futon đã bị bạn xé nát.", "talkname0", 1);
    Talk(53, "Huh! Trong tấm nệm này hình như có một cái túi lụa giấu, phía trên có viết chữ... "Nếu ngươi đã quỳ lạy ngàn lần, hẳn là bị ta dắt đi, cả đời ngươi sẽ không hối hận. Quyển sách này là bản chất võ thuật của giáo phái Tiêu Dao của ta, và nó nên được đọc hàng ngày tại Mao Wu You Ba lần một ngày, bạn phải luyện tập nó bằng cả trái tim mình ... "", "talkname53", 1);
    Talk(0, "Ở đây hình như có hai cuốn sách nhỏ, một cuốn tên là "Bắc Minh Thần Kỹ", một cuốn tên là "Lingbo Weibu".", "talkname0", 1);
    Talk(53, "＜Tôi không muốn học võ, nhưng làm sao tôi có thể trái lệnh tiên nữ? Tôi quỳ lạy cô ấy cả nghìn lần, nghĩa là tôi đồng ý để anh ấy dẫn đi và tuân theo mệnh lệnh của cô ấy. Đầu tiên tôi sẽ đọc những gì được viết trong sách > "Có những kẻ ở trong biển tối ở phía bắc nghèo khó... Thần thông của Beiming thu hút sức mạnh của thế giới và là của tôi. Nước lớn ở phía bắc không thể tự nó trỗi dậy Tục ngữ có câu: Trăm sông hội tụ. Biển, nước biển có được nhờ chứa trăm sông. Đại dương bao la đang thấm nhuần, và đang tích tụ. Kinh mạch Thái Âm Long trong tay này là bài học đầu tiên của Bắc Minh Thần kỹ... Trên đó còn có một số sơ đồ châm cứu, trên đó có sọc xanh....... Hừ! Tại sao cơ thể tôi có chút nóng...Trong một cuốn sách khác "Lingbo Weibu ", trên đó có rất nhiều dấu chân được vẽ, và một số chỉ dẫn trong Kinh Dịch cũng được đánh dấu, đúng là tôi mới học Kinh Dịch mấy ngày trước, việc này có vẻ dễ dàng hơn nhiều...", "talkname53", 1);
    DarkScence();
    LightScence();
    Talk(53, "Tiên nữ, ngươi ra lệnh cho ta sáng trưa tối luyện ba lượt, Đoàn Dự không dám trái lệnh.", "talkname53", 1);
    Talk(0, "Anh Duẩn đã hiểu ra và sẵn sàng luyện tập võ thuật.", "talkname0", 1);
    Talk(53, "Nhưng từ nay trở đi, tôi sẽ khách khí hơn với mọi người, người khác sẽ không đến đánh tôi, tôi đương nhiên sẽ không hấp thụ nội lực của họ. Về phần "Lingbo Weibu" này, tôi phải luyện tập cẩn thận hơn, nếu thấy sai tôi sẽ bỏ chạy ngay lập tức.", "talkname53", 1);
    Talk(0, "Tùy cậu thôi, đi thôi.", "talkname0", 1);
    DarkScence();
    ModifyEvent(-2, 11, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
    jyx2_ReplaceSceneObject("", "NPC/段誉11", "");--段誉归队
    LightScence();
    AddItem(63, 1);
    AddItem(47, 1);
    LearnMagic2(53, 29, 0);
    AddSpeed(53, 30);
    AddAttack(53, 10);
    AddAptitude(53, 20);
    SetPersonMPPro(53,2);
    ModifyEvent(-2, 1, -2, -2, 485, -1, -1, -2, -2, -2, -2, -2, -2);
    ModifyEvent(-2, 2, 1, 1, -1, -1, -1, 6752, 6752, 6752, -2, -2, -2);
    jyx2_ReplaceSceneObject("", "NPC/蟒牯朱蛤", "1");
    ModifyEvent(-2, 3, -2, -2, -1, -1, 486, -2, -2, -2, -2, -2, -2);
    ModifyEvent(-2, 4, -2, -2, -1, -1, 486, -2, -2, -2, -2, -2, -2);
    ModifyEvent(-2, 5, -2, -2, -1, -1, 486, -2, -2, -2, -2, -2, -2);
    SetScenceMap(52, 1, 27, 28, 1842);
    SetScenceMap(52, 1, 27, 20, 1838);
    SetScenceMap(52, 1, 27, 29, 0);
	jyx2_FixMapObject("燕子坞开门",1);
    PlayWave(21);
do return end;
