Talk(0, "Người xưa nói phía trên có thiên đường, phía dưới có Tô Châu, Hàng Châu, phong cảnh Hồ Tây thật là dễ chịu, Mộ Dung tiên sinh sống ở đây, có mỹ nhân đi cùng, ông ấy thực sự rất may mắn.", "talkname0", 1);
Talk(51, "Bạn là ai và tại sao bạn lại ở Yanziwu?", "talkname51", 0);
Talk(0, "Tên của tôi không đáng nhắc tới, tôi lang thang khắp thế giới chỉ để trở về tương lai, hôm nay tôi đến đây để xin Mộ Dung tiên sinh một lời khuyên.", "talkname0", 1);
Talk(51, "Nếu bạn có điều gì muốn nói, cứ nói đi.", "talkname51", 0);
Talk(0, "Trong thiên hạ có tin đồn rằng gia tộc Mộ Dung ở Cô Tô có một bộ sưu tập sách rất phong phú, bao gồm tất cả những cuốn sách võ thuật hiếm có trên thế giới...", "talkname0", 1);
Talk(51, "Thì ra tôi muốn xem bí quyết võ công phong phú của Mộ Dung gia tôi...", "talkname51", 0);
Talk(0, "Mộ Dung tiên sinh hiểu lầm, ta tìm không phải một ít võ công bí truyền, mà chỉ là mấy cuốn tiểu thuyết mà thôi.", "talkname0", 1);
Talk(51, "Ý bạn là...", "talkname51", 0);
Talk(0, "Mọi người đều cho rằng Thập Tứ Thiên Thư là một bí thư võ công thâm sâu nào đó, kỳ thực theo chỗ tôi biết thì chỉ là một vài cuốn tiểu thuyết mà thôi. Không biết gia đình Mộ Dung có sưu tầm những cuốn sách này không?", "talkname0", 1);
Talk(51, "Rất tiếc, bộ sưu tập sách ở Yanziwu không có thứ bạn muốn.", "talkname51", 0);
Talk(0, "Ồ! Đây là những gì nó trông giống như ...", "talkname0", 1);
Talk(51, "Nhưng……", "talkname51", 0);
Talk(0, "Nhưng cái gì...", "talkname0", 1);
Talk(51, "Nhưng tôi biết nơi cất giữ một trong những cuốn sách...", "talkname51", 0);
Talk(0, "Cuốn sách nào?", "talkname0", 1);
Talk(51, "\"Rồng\".", "talkname51", 0);
Talk(0, "thực tế? Ở đâu?", "talkname0", 1);
Talk(51, "Tôi tự hỏi liệu bạn đã bao giờ nghe nói về những kỹ năng độc đáo của gia đình Mộ Dung của tôi chưa.", "talkname51", 0);
Talk(0, "Chà, mọi người trên thế giới đều nói rằng Gusu Murong \"trả ơn người khác bằng chính phương pháp của mình\".", "talkname0", 1);
Talk(51, "Vâng, trong trường hợp này, bạn biết phải làm gì.", "talkname51", 0);
Talk(0, "Ý bạn là...", "talkname0", 1);
Talk(51, "Nếu bạn giúp tôi tìm thứ gì đó, tôi sẽ cho bạn biết tung tích của \"Dragon Babu\".", "talkname51", 0);
Talk(0, "Ta sợ chết khiếp, ta còn tưởng rằng ngươi sẽ dùng võ công ta giỏi đối phó với ta... Ngươi biết đấy, ta biết rất nhiều võ thuật... Chỉ sợ không dễ dàng như vậy.\" bạn phải \"trả ơn người khác bằng phương pháp tương tự.\"", "talkname0", 1);
Talk(51, "Ngài đã cười.", "talkname51", 0);
Talk(0, "Không biết thiếu gia đang tìm cái gì?", "talkname0", 1);
Talk(51, "Con dấu ngọc được truyền lại từ Vương quốc Yan.", "talkname51", 0);
Talk(0, "Con dấu hoàng gia được truyền lại từ Vương quốc Yan? Ông Mộ Dung là người sưu tập đồ cổ phải không? Vì sao muốn có ngọc ấn của \"Đại Yến Quốc\"? Ngươi không phải hoàng đế, ngọc ấn có tác dụng gì?", "talkname0", 1);
Talk(51, "Im đi, tôi là cháu trai của Hoàng tử Mộ Dung nước Dayan.", "talkname51", 0);
Talk(0, "Xin lỗi xin lỗi.", "talkname0", 1);
Talk(109, "Em ơi, tại sao em vẫn nghĩ đến việc khôi phục đất nước?", "talkname109", 0);
Talk(51, "Làm sao chúng ta có thể quên được lời dạy của tổ tiên qua các thời đại?", "talkname51", 0);
Talk(0, "Cô gái này giống như một nàng tiên, không rõ tên...", "talkname0", 1);
Talk(51, "Đây là anh họ của tôi Wang Yuyan. Cô quen thuộc với bản chất của các trường phái võ thuật, mặc dù không biết bất kỳ môn võ thuật nào nhưng cô có kiến thức sâu rộng về võ thuật.", "talkname51", 0);
Talk(0, "Chào cô Vương...", "talkname0", 1);
ModifyEvent(-2, 2, -2, -2, -2, -2, -2, 6298, -2, -2, -2, -2, -2); --记录改变贴图，Ka941 JudgeScenePic
if InTeam(53) == true then goto label0 end;
    Talk(51, "Hãy nhớ rằng, nếu bạn muốn biết tung tích của \"Bát Thiên Long\", bạn nên đi tìm phong ấn hoàng gia của Vương quốc Dayan.", "talkname51", 0);
    ModifyEvent(-2, -2, -2, -2, 489, 493, -1, -2, -2, -2, -2, -2, -2);
    ModifyEvent(-2, 2, -2, -2, 490, -1, -1, -2, -2, -2, -2, -2, -2);
    do return end;
::label0::
    jyx2_ReplaceSceneObject("", "NPC/段誉", "1");--段誉
    Talk(53, "Tiên nữ... Tiên nữ... Tiểu Sinh Đoàn Dự nhớ ngươi quá!", "talkname53", 1);
    Talk(109, "cái này…………", "talkname109", 0);
    Talk(51, "Bạn đang làm gì vậy, đồ ngốc, nhìn anh họ của tôi như thế này?", "talkname51", 0);
    Talk(0, "Mộ Dung tiên sinh, xin hãy bình tĩnh, các anh của tôi đã nhận nhầm người rồi, chỉ là…chỉ là họ thực sự giống nhau mà thôi…", "talkname0", 1);
    Talk(51, "như thế nào?", "talkname51", 0);
    Talk(0, "Không, ý tôi là anh họ Ling trông rất giống một người, một bức tượng ngọc mà chúng tôi tìm thấy ở núi Wuliang, nó rất giống.", "talkname0", 1);
    Talk(53, "Tiên nữ... sao chị không nói chuyện với em... chị có thể đi cùng chúng em được không?", "talkname53", 1);
    Talk(109, "Không, tôi muốn đi theo anh họ tôi.", "talkname109", 0);
    Talk(0, "Anh Duẩn, đừng thô lỗ nữa. Ông Mộ Dung, chúng tôi đi đây.", "talkname0", 1);
    Talk(51, "Hãy nhớ rằng, nếu bạn muốn biết tung tích của \"Bát Thiên Long\", bạn nên đi tìm phong ấn hoàng gia của Vương quốc Dayan.", "talkname51", 0);
    jyx2_ReplaceSceneObject("", "NPC/段誉", "");--段誉
    ModifyEvent(-2, -2, -2, -2, 489, 493, -1, -2, -2, -2, -2, -2, -2);
    ModifyEvent(-2, 2, -2, -2, 490, -1, -1, -2, -2, -2, -2, -2, -2);
    ModifyEvent(-2, 0, -2, -2, -1, -1, 491, -1, -1, -1, -2, -2, -2);
do return end;
