Talk(0, "Anh hai, quán trọ Long Môn của anh làm ăn rất phát đạt, nơi đây đông đúc khách. Có món ăn nào đặc trưng đích thực hay có cô chủ quán nào quyến rũ để thu hút khách hàng?", "talkname0", 1);
Talk(106, "Chàng trai trẻ này, hãy để tôi nói cho bạn sự thật. Ngày xửa ngày xưa, chủ nhân của quán trọ Long Môn quả thực là một mỹ nhân quyến rũ. Nhưng kể từ khi ông chủ của chúng tôi tiếp quản cửa hàng này, việc kinh doanh ngày càng sa sút. Ai gọi về Miền Tây xa xôi?", "talkname106", 0);
Talk(0, "Nhưng tôi thấy có rất nhiều khách hàng trong cửa hàng!", "talkname0", 1);
Talk(106, "bạn không biết là? Gần đây có rất nhiều người từ phía đông tới, hình như là người của các giáo phái khác nhau ở Trung Nguyên.", "talkname106", 0);
Talk(0, "Họ đang đi đâu vậy?", "talkname0", 1);
Talk(106, "Suỵt! Cậu nhỏ giọng đi... Ta nghe lỏm được điều gì đó... Bọn họ hình như là đệ tử của sáu giáo phái, lần này đến Tây Vực, bọn họ hình như là đến tấn công Minh giáo, nói rằng sáu giáo phái lớn đang vây hãm Quảng Minh Đỉnh.", "talkname106", 0);
Talk(0, "Sáu thế lực lớn bao vây Quảng Minh Đỉnh?", "talkname0", 1);
Talk(106, "Hãy giữ giọng nói nhỏ và đừng gặp rắc rối. Người phục vụ, tôi khuyên anh không nên ở lại đây nếu không có việc gì làm, khu vực phía Tây gần đây đã trở thành một nơi rắc rối.", "talkname106", 0);
ModifyEvent(-2, -2, -2, -2, 500, -1, -1, -2, -2, -2, -2, -2, -2);
do return end;
