Talk(0, "Đây có phải là Bang chủ Qiao không?", "talkname0", 1);
Talk(50, "Tốt lắm, tuổi còn trẻ đã phá vỡ trận đấu chó của băng nhóm ăn xin của tôi, ngày nay giới trẻ ngày càng mạnh mẽ.", "talkname50", 0);
Talk(0, "Ở đâu, so với Bang chủ Qiao, người lãnh đạo rất nhiều anh hùng, tôi vẫn còn kém xa.", "talkname0", 1);
Talk(50, "Một lũ ăn xin, chẳng có gì cả. Không biết anh hùng trẻ tuổi có việc gì quan trọng khi đến Bang Ăn mày của chúng ta không?", "talkname50", 0);
Talk(0, "Nó không có gì đặc biệt. Đứa em trai này mới đến thế giới này, đương nhiên phải đến thăm Gia tộc ăn mày, nếu không thì làm sao có thể được gọi là thành viên của thế giới?", "talkname0", 1);
Talk(50, "Tôi tự hỏi cảm giác du lịch đến Jianghu như thế nào?", "talkname50", 0);
Talk(0, "Vừa đắng vừa ngọt. Có rất nhiều việc cần giải quyết nhưng tôi cũng học được rất nhiều võ công, càng ngày tôi càng cảm thấy mãn nguyện. Tuy nhiên, trong thế giới sông hồ, lòng người nham hiểm, nhưng chúng ta không thể thoát khỏi thế giới sông hồ, quả thật có câu “người ở thế giới sông hồ không thể tự giúp mình”.", "talkname0", 1);
Talk(50, "ha! ha! Nói hay, nói hay, đừng nhắc tới những chuyện khó chịu này nữa, chúng ta uống đi.", "talkname50", 0);
if InTeam(35) == false then goto label0 end;
    Talk(35, "Vâng, anh trai, chúng ta hãy uống một ly với Bang chủ Kiều.", "talkname35", 1);
::label0::
    Talk(0, "Tốt.", "talkname0", 1);
    DarkScence();
    LightScence();
    Talk(50, "Anh hùng trẻ tuổi dường như đã đề cập đến, có rất nhiều điều chưa được giải quyết, và anh ấy lo lắng về chúng, anh ấy không biết chúng là gì.", "talkname50", 0);
    Talk(0, "Chuyện thì dài, nhưng tóm lại là hiện giờ tôi đang tìm cuốn “Sách Mười Bốn Ngày” đã trở thành huyền thoại trong nhân gian.", "talkname0", 1);
    Talk(50, "Thì ra là như vậy, xem ra rất khó khăn.", "talkname50", 0);
    Talk(0, "Đúng.", "talkname0", 1);
    Talk(50, "Đừng lo lắng về điều này, những cuốn sách sẽ luôn được tìm thấy, có lẽ tôi, Qiao Feng, sau này cũng có thể đóng góp một chút.", "talkname50", 0);
    Talk(0, "Có Kiều bang chủ giúp đỡ, tôi cũng yên tâm hơn. Trong trường hợp đó, tôi sẽ nghỉ phép trước.", "talkname0", 1);
    Talk(50, "Đi chậm.", "talkname50", 0);
    ModifyEvent(-2, -2, -2, -2, 526, -1, -1, -2, -2, -2, -2, -2, -2);
do return end;
