PlayAnimation(3, 6342, 6348);
jyx2_SwitchRoleAnimation("NPC/suxinghe", "Assets/BuildSource/AnimationControllers/KneelController.controller");
Talk(52, "Su Xinghe, một đệ tử vô đạo đức của Giáo phái Tiêu Dao, tỏ lòng kính trọng với người đứng đầu mới của giáo phái.", "talkname52", 0);
Talk(49, "Ông già sẽ giết vị hòa thượng trẻ nếu thực hiện món quà tuyệt vời này.", "talkname49", 0);
Talk(52, "Sư đệ, ngươi là đệ tử thân cận của sư phụ ta, là thủ lĩnh của giáo phái chúng ta. Dù là sư huynh nhưng ta vẫn muốn quỳ lạy ngươi!", "talkname52", 0);
Talk(49, "Cái này...cái này...", "talkname49", 0);
Talk(52, "Sư phụ yêu cầu bạn tôn thờ Ngài như thầy của bạn và yêu cầu bạn lạy chín lần. Bạn đã lạy chưa?", "talkname52", 0);
Talk(49, "Tôi lạy lạy nhưng lúc đó tôi không biết mình là đệ tử. Tôi là đệ tử của môn phái Thiếu Lâm và không thể chuyển sang môn phái khác.", "talkname49", 0);
Talk(52, "Sư phụ đương nhiên cũng nghĩ tới việc này, nhất định là đã lấy đi võ công nguyên bản của ngươi, dạy cho ngươi chiêu thức võ công của chính hắn. Sư phụ đã truyền lại những kỹ năng cả đời của mình cho bạn phải không?", "talkname52", 0);
Talk(49, "Đúng.", "talkname49", 0);
Talk(52, "Chiếc nhẫn đá quý tượng trưng cho người đứng đầu giáo phái này là do chính tay Sư phụ lấy ra và đưa cho ngươi đeo phải không?", "talkname52", 0);
Talk(49, "Đúng! Nhưng... nhưng tôi thực sự không biết đây là loại token gì từ người đứng đầu.", "talkname49", 0);
Talk(52, "Tiểu đệ đệ, ngươi thật sự có phúc. Tôi và Ding Chunqiu đã suy nghĩ về chiếc nhẫn đá quý này hàng chục năm nhưng chúng tôi chưa bao giờ có được nó, tuy nhiên, chỉ trong vòng một giờ, bạn đã được Sư phụ sủng ái.", "talkname52", 0);
Talk(49, "Tiền bối, cứ lấy đi. Chiếc nhẫn này chẳng có tác dụng gì với nhà sư cả.", "talkname49", 0);
Talk(52, "Sư đệ, ngươi trước khi chết được sư phụ giao phó, sao có thể trốn tránh trách nhiệm? Sư phụ đã trao cho bạn chiếc nhẫn để giết Đinh Xuân Thu phải không?", "talkname52", 0);
Talk(49, "Chính xác. Nhưng làm thế nào một tu sĩ trẻ có thể đảm nhận một nhiệm vụ quan trọng như vậy nếu công đức của anh ta còn nông cạn?", "talkname49", 0);
Talk(0, "Anh thân mến, không ngờ anh đã giành được giải thưởng lớn và trở thành người đứng đầu.", "talkname0", 1);
Talk(49, "Anh em trai...", "talkname49", 0);
ModifyEvent(-2, -2, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
do return end;
