Talk(0, "Anh trai thân mến, chuyện gì đang xảy ra vậy? Ông già nằm trên mặt đất đó là ai?", "talkname0", 1);
Talk(49, "Bản thân tôi cũng bối rối. Sau khi tôi bước vào nhà, trong nhà có một ông già nói rằng tôi rất may mắn và đã phá được ván cờ. Sau đó, nó làm cứng đi võ thuật ban đầu của tôi và truyền võ học hơn bảy mươi năm của ông vào cơ thể tôi.", "talkname49", 0);
Talk(0, "Có một điều như vậy.", "talkname0", 1);
Talk(49, "Anh ta cũng yêu cầu tôi giết Ding Chunqiu, con quái vật cũ của Xingxiu.", "talkname49", 0);
Talk(0, "Tiền bối Su, chuyện gì đang xảy ra vậy?", "talkname0", 1);
Talk(52, "Đây là cách nó diễn ra. Giáo phái của chúng tôi là giáo phái Tiêu Dao, sư phụ đã nhận tôi và Đinh Xuân Thu làm hai đệ tử. Sư phụ của ta có một quy tắc, bởi vì hắn học nhiều như vậy, muốn làm thủ lĩnh đều phải thi đấu đủ loại kỹ năng, không chỉ võ thuật mà còn cả piano, cờ vua, thư pháp và hội họa. Nhưng Ding Chunqiu không biết gì về các loại nghiên cứu linh tinh, thấy người đứng đầu không còn hy vọng, anh ta đột nhiên âm mưu đánh sư phụ của mình xuống vực sâu và làm tôi bị thương nặng.", "talkname52", 0);
Talk(0, "Người đàn ông này thật sự rất đáng ghét.", "talkname0", 1);
Talk(52, "Sau này, sư phụ nhân cơ hội giả chết, bày lại ván cờ này, hy vọng tìm được người có hiểu biết cao. Hãy để anh ta trở thành người lãnh đạo và dạy anh ta các kỹ năng của mình để anh ta có thể thoát khỏi tên trộm độc ác Ding Chunqiu trong tương lai. Hôm nay, cuối cùng chúng ta cũng có người có thể bẻ khóa Zhenlong này, sư phụ cũng đã qua đời sau khi truyền lại kỹ năng cho ông ta. Sư đệ, người đứng đầu Tiêu Dao phái, việc dọn dẹp cửa môn Tiêu Dao chúng ta là việc của ngươi.", "talkname52", 0);
Talk(49, "Tôi đánh nhầm và không hiểu gì cả. Huống chi ta là đệ tử Thiếu Lâm, làm sao có thể chuyển sang môn phái khác?", "talkname49", 0);
Talk(0, "Người anh đức hạnh của tôi tuy không hiểu biết nhưng lại rất “lầm lẫn”, tôi không nghĩ bạn nên đi tu, làm người đứng đầu cũng không phải là một ý kiến hay.", "talkname0", 1);
Talk(49, "Nhưng……", "talkname49", 0);
Talk(0, "Quên đi, ngươi xem, lão nhân này qua đời là vì muốn truyền lại kỹ năng cả đời cho ngươi, ngươi còn nỡ từ chối hắn sao? Bên cạnh đó, Ding Chunqiu còn là một kẻ phản diện phạm đủ mọi tội ác và phạm những tội ác không thể tha thứ.", "talkname0", 1);
Talk(49, "……", "talkname49", 0);
Talk(0, "Được rồi, tôi nghĩ thế là xong. Tô tiền bối, chúng ta sẽ đi tìm Tinh Tú lão quái vật kia, giết hắn để báo thù cho chủ nhân của ngươi.", "talkname0", 1);
Talk(52, "Ông lão cảm ơn người anh hùng trẻ tuổi đã giúp đỡ. Thiếu gia, xin hãy cẩn thận trên đường đến đây, tên trộm già Đinh Xuân Thu đang hành động hèn hạ... Nhân tiện, tôi có một người học việc là bác sĩ Xue, người có tay nghề cao về y học và được mệnh danh là "Kẻ thù của kẻ thù". Vua địa ngục". Bạn có thể đến gặp anh ta để được giúp đỡ. Khi nhìn thấy anh ta, bạn chỉ cần đưa ra "Chiếc nhẫn bảy báu" làm biểu tượng của người lãnh đạo.", "talkname52", 0);
DarkScence();
ModifyEvent(-2, 1, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
jyx2_ReplaceSceneObject("", "NPC/xiaoyaozi", "");--逍遥子1
ModifyEvent(-2, 2, 1, 1, 581, -1, -1, 6522, 6522, 6522, -2, -2, -2);
ModifyEvent(-2, 3, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
ModifyEvent(-2, 0, 1, 1, 537, -1, -1, 6340, 6340, 6340, -2, -2, -2);
ModifyEvent(35, 3, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
jyx2_FixMapObject("逍遥子传功完毕",0);
jyx2_SwitchRoleAnimation("NPC/suxinghe", "Assets/BuildSource/AnimationControllers/sit_on_chair.controller");
jyx2_ReplaceSceneObject("35","NPC/星宿弟子3","");
NPCAddItem(49, 128, 1);
NPCAddItem(49, 56, 1);
NPCAddItem(49, 40, 1);
LightScence();
Talk(0, "Anh em thân mến, chúng ta đi thôi.", "talkname0", 1);
if TeamIsFull() == false then goto label0 end;
    Talk(49, "Nhóm của bạn đã đầy đủ và tôi không thể tham gia.", "talkname49", 0);
    do return end;
::label0::
    DarkScence();
    jyx2_ReplaceSceneObject("", "NPC/xuzhu", "");--虚竹加入
    ModifyEvent(-2, 2, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
    LightScence();
    AddMp(49, 300);
    AddHp(49, 200);
    AddAttack(49, 30);
    AddSpeed(49, 20);
    LearnMagic2(49, 15, 0);
    SetPersonMPPro(49,2);
    Join(49);
    ModifyEvent(28, 0, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
    ModifyEvent(28, 1, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
    ModifyEvent(28, 2, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
    ChangeMMapMusic(3);
do return end;
