if InTeam(47) == false then goto label0 end;
    Talk(46, "A Tử, ngươi thật dám quay lại. Còn “Vạc Vương Mộc Mộc” thì sao?", "talkname46", 0);
    jyx2_ReplaceSceneObject("","NPC/阿紫2","1");
::label0::
    Talk(0, "＜Sao trông bạn giống trẻ con quá vậy, chẳng lẽ bạn đã thực sự luyện tập đến mức trẻ lại rồi sao? >Ding Chunqiu, bạn có nhận ra chiếc nhẫn Thất Bảo này không?", "talkname0", 1);
    Talk(46, "Bạn là ai và tại sao bạn lại có thứ này?", "talkname46", 0);
    Talk(0, "Anh ta thậm chí còn không quỳ xuống khi nhìn thấy người lãnh đạo.", "talkname0", 1);
    Talk(46, "Thủ lĩnh của Giáo phái Tiêu Dao đã đánh cắp mã thông báo của anh ta ở đâu?", "talkname46", 0);
    Talk(0, "Nó là do sư phụ của ngươi đưa cho, ông ta muốn chúng ta dọn dẹp nhà cửa cho hắn và loại bỏ ngươi, kẻ cặn bã võ thuật.", "talkname0", 1);
    Talk(46, "Tên trộm già bị ta đánh rơi khỏi vách đá nhưng hắn vẫn còn sống và trao cho bạn chiếc nhẫn Thất Bảo. Không sao, ngươi tự mình đến chết, ta liền không cần đi tìm Thất Bảo Nhẫn.", "talkname46", 0);
    Talk(92, "Bản lĩnh của sư phụ chấn động quá khứ và hiện tại, sao dám chống lại chúng ta, đây gọi là đom đóm tranh giành vinh quang với mặt trời và mặt trăng!", "talkname92", 0);
    Talk(92, "Thật nực cười khi chặn xe bằng cánh tay của bọ ngựa và đánh giá quá cao khả năng của mình! lố bịch!", "talkname92", 0);
    Talk(92, "Chủ nhân của tôi có thể giết chết những con quái vật và hề chỉ bằng cách nói và cười...", "talkname92", 0);
    Talk(0, "Bạn có phiền không? Muốn đánh nhau thì đánh nhanh lên. Đừng khoe khoang về điều đó.", "talkname0", 1);
    if TryBattle(86) == true then goto label1 end;
        Dead();
        do return end;
::label1::
        ModifyEvent(-2, 0, 1, 1, 590, -1, -1, 6600, 6600, 6600, -2, 39, 28);
        ModifyEvent(-2, 1, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
        ModifyEvent(-2, 2, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
        jyx2_FixMapObject("丁春秋战死",1);
		jyx2_SwitchRoleAnimation("NPC/dingchunqiu", "Assets/BuildSource/AnimationControllers/Dead-FaceUp.controller");
		jyx2_ReplaceSceneObject("","NPC/阿紫2","");
        ModifyEvent(-2, 4, -2, -2, 547, -1, -1, -2, -2, -2, -2, -2, -2);
        ModifyEvent(-2, 5, -2, -2, 548, -1, -1, -2, -2, -2, -2, -2, -2);
        ModifyEvent(-2, 6, -2, -2, 549, -1, -1, -2, -2, -2, -2, -2, -2);
        ModifyEvent(-2, 7, -2, -2, 550, -1, -1, -2, -2, -2, -2, -2, -2);
        ModifyEvent(-2, 8, -2, -2, 547, -1, -1, -2, -2, -2, -2, -2, -2);
        ModifyEvent(-2, 9, -2, -2, 548, -1, -1, -2, -2, -2, -2, -2, -2);
        ModifyEvent(-2, 10, -2, -2, 549, -1, -1, -2, -2, -2, -2, -2, -2);
        ModifyEvent(-2, 12, -2, -2, 550, -1, -1, -2, -2, -2, -2, -2, -2);
        ModifyEvent(-2, 13, -2, -2, 547, -1, -1, -2, -2, -2, -2, -2, -2);
        ModifyEvent(-2, 14, -2, -2, 548, -1, -1, -2, -2, -2, -2, -2, -2);
        ModifyEvent(53, 0, -2, -2, 538, -1, -1, -2, -2, -2, -2, -2, -2);
        LightScence();
        Talk(0, "Cuối cùng cũng thoát khỏi con quái vật già này.", "talkname0", 1);
        Talk(92, "Người anh hùng trẻ tuổi là bất khả chiến bại, trong khi kẻ ác lại trung thành, tận tụy và sẵn sàng phục vụ chủ nhân của mình hết mình như chó hay ngựa.", "talkname92", 0);
        Talk(92, "Vị trí thủ lĩnh của liên minh ở thế giới này không ai khác chính là người anh hùng trẻ tuổi. Chỉ cần chủ nhân ra lệnh hành động, kẻ ác sẽ đi qua lửa và nước, dù có chết đến đâu.", "talkname92", 0);
        Talk(92, "Đinh Xuân Thu sáng như ngọn nến, dám cạnh tranh với mặt trời và mặt trăng.", "talkname92", 0);
        Talk(92, "Thiếu niên anh hùng đức độ xứng đáng trời đất, cường đại thiên hạ, cổ đại vô song.", "talkname92", 0);
        Talk(0, "Những kẻ này tốc độ nhanh như vậy, thật xứng đáng làm đệ tử của phái Tinh Tú. Mặc dù nghe có vẻ hơi tê nhưng lại khá thoải mái.", "talkname0", 1);
        AddEthics(10);
        AddRepute(6);
do return end;
