ScenceFromTo(44, 24, 36, 24);
jyx2_CameraFollow("Level/NPC/azi");
Talk(92, "Sư phụ đã ra lệnh cho ta đưa ngươi trở về, tiểu sư muội, ngươi định trái lệnh sư phụ sao?", "talkname92", 0);
Talk(47, "Nhị sư huynh, ngươi biết sư phụ tức giận, còn ép ta trở về, chẳng phải là muốn ta đau khổ sao?", "talkname47", 0);
Talk(92, "Vì cậu nhất quyết không quay lại nên hãy đưa thứ đó cho tôi. Tôi sẽ lấy lại và đưa cho Sư phụ để tôi có thể giải thích.", "talkname92", 0);
Talk(47, "Bạn nói gì? Vật nào? Nhân tiện, thứ đó đã bị cậu bé phía sau lấy đi rồi.", "talkname47", 0);
Talk(92, "Con trai! Hãy nhanh chóng tiêu diệt "Vạc Vương Mộc Thánh"!", "talkname92", 0);
ScenceFromTo(36, 24, 44, 24);
jyx2_CameraFollowPlayer();
Talk(0, ""Cây thiêng" nào...", "talkname0", 1);
Talk(47, "Nhị sư huynh, ngươi xem, cho dù bị hắn cướp đi, hắn cũng sẽ không lấy ra.", "talkname47", 0);
Talk(92, "Thế thì đừng trách chúng tôi vô lý nhé.", "talkname92", 0);
Talk(0, "Này, đừng tùy tiện đánh người...", "talkname0", 1);
if TryBattle(87) == true then goto label0 end;
    Dead();
    do return end;
::label0::
    ModifyEvent(-2, 5, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
    ModifyEvent(-2, 6, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
    ModifyEvent(-2, 7, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
    ModifyEvent(-2, 8, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
    ModifyEvent(-2, 9, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
    jyx2_ReplaceSceneObject("", "NPC/星宿弟子5", "");
    jyx2_ReplaceSceneObject("", "NPC/星宿弟子6", "");
    jyx2_ReplaceSceneObject("", "NPC/星宿弟子7", "");
    jyx2_ReplaceSceneObject("", "NPC/星宿弟子8", "");
    jyx2_ReplaceSceneObject("", "NPC/星宿弟子9", "");
    ModifyEvent(-2, 4, -2, -2, -2, -1, -1, 6378, 6378, 6378, -2, 35, 24);
    jyx2_SwitchRoleAnimation("NPC/youtanzhi", "Assets/BuildSource/AnimationControllers/StandController.controller");
    jyx2_FixMapObject("移到阿紫身边", 1);
    SetScencePosition2(37, 25);
	jyx2_MovePlayer("战斗后","Level/Dynamic");
    LightScence();
    Talk(0, "Cô gái, chuyện gì đang xảy ra vậy?", "talkname0", 1);
    Talk(47, "Sư huynh và những người khác muốn giết ta, nhưng ngươi đã chạy ra cứu ta.", "talkname47", 0);
    Talk(0, "Bạn nói mình lấy loại chân máy thần mộc vương nào đó nhưng mình không lấy.", "talkname0", 1);
    Talk(47, "Tôi đã nói dối họ, nếu không thì làm sao bạn có thể cứu tôi.", "talkname47", 0);
    Talk(0, "Chuyện này... trò đùa này chắc lớn quá. Nếu tôi không thể đánh bại họ thì sao? Chẳng phải tôi đã chết vô ích dưới tay họ sao?", "talkname0", 1);
    Talk(47, "Nếu bạn thậm chí không thể đánh bại họ, bạn cũng có thể chết.", "talkname47", 0);
    Talk(0, "Bạn...bạn đang nói về cái gì vậy?", "talkname0", 1);
    Talk(47, "Tôi sẽ không nói với bạn nữa. Thiết Châu, ngươi bắt được "con tằm băng" ở đâu vậy, ta cũng muốn lấy một con để luyện tập, nhất định có hiệu quả rất lớn.", "talkname47", 0);
    Talk(48, "Tôi nghe vị sư béo bắt được “con tằm băng” nói rằng “con tằm băng” đến từ dãy núi Côn Lôn.", "talkname48", 0);
    Talk(47, "Tất cả là tại ngươi mà ngươi đã hút tinh hoa "Băng Tằm" vào cơ thể ta, khiến ta không thể luyện khí công.", "talkname47", 0);
    Talk(48, "Vâng, tất cả đều nhỏ, không.", "talkname48", 0);
    Talk(0, "＜Cô bé này có lẽ đang luyện tập một loại kung fu độc ác nào đó＞", "talkname0", 1);
    Talk(47, "Này, sao cậu không rời đi? Cậu đang làm gì ở đây?", "talkname47", 0);
    Talk(48, "Cô Azi yêu cầu bạn rời đi, nhưng bạn vẫn chưa rời đi.", "talkname48", 0);
    Talk(0, "Tại sao bạn lại tàn nhẫn như vậy? Tôi đã cứu bạn và bạn vẫn độc ác như vậy. Đó thực sự là một ý định tốt mà không được đền đáp.", "talkname0", 1);
    Talk(47, "Yo, khá là cá tính. Thiết Châu, bắt hắn, giúp hắn đội mũ trùm đầu, trở thành nô lệ của ta.", "talkname47", 0);
    Talk(48, "Cô Azi, một mình tôi phục vụ cô là đủ rồi, không cần tìm người khác.", "talkname48", 0);
    Talk(47, "Dù bạn nói gì, hãy làm bất cứ điều gì bạn được bảo.", "talkname47", 0);
    Talk(48, "Đúng.", "talkname48", 0);
    Talk(0, "Thật sự là nói dối quá đáng, bạn nghĩ tôi là diễn viên trong phim "hạn chế", tại sao tôi phải đội mũ đội đầu?", "talkname0", 1);
    if TryBattle(88) == true then goto label1 end;
        Dead();
        do return end;
::label1::
        LightScence();
        Talk(48, "Cô Azi, tôi xin lỗi, tôi không thể đánh bại anh ta.", "talkname48", 0);
        Talk(47, "người ăn khỏe.", "talkname47", 0);
        Talk(0, "＜Thật xui xẻo khi tôi gặp phải một kẻ tâm thần＞Hãy rời đi.", "talkname0", 1);
        ModifyEvent(-2, 3, -2, -2, 558, 560, -1, -2, -2, -2, -2, -2, -2);
        ModifyEvent(-2, 4, -2, -2, 559, -1, -1, -2, -2, -2, -2, -2, -2);
        ModifyEvent(-2, 0, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
        ModifyEvent(-2, 1, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
        ModifyEvent(-2, 2, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
        AddEthics(2);
        AddRepute(2);
do return end;
