if UseItem(131) == true then goto label0 end;
    do return end;
::label0::
    AddEthics(2);
    AddItemWithoutHint(131, -1);
    Talk(51, "Haha, với bảng gia phả của Hoàng đế Đại Diễn và con dấu ngọc được truyền lại cho đất nước, tôi có thể kêu gọi con cháu Đại Diễn thực hiện kế hoạch khôi phục đất nước.", "talkname51", 0);
    Talk(0, "Lần này Mộ Dung tiên sinh sẽ không thất hứa nữa.", "talkname0", 1);
    Talk(51, "Ta, Mộ Dung Phục, có bao giờ thất hứa đâu?", "talkname51", 0);
    Talk(0, "＜Người cao quý thường hay quên đồ＞", "talkname0", 1);
    Talk(51, "Nơi cất giữ cuốn sách \"Rồng và tám phần\" là...", "talkname51", 0);
    Talk(0, "Ở đâu?", "talkname0", 1);
    Talk(51, "Trong tay Kiều Phong.", "talkname51", 0);
    Talk(0, "Bạn đang nói về Qiao Feng, thủ lĩnh của Bang ăn xin?", "talkname0", 1);
    Talk(51, "Chính xác.", "talkname51", 0);
    Talk(0, "Bạn không thể chỉ nói điều đó một cách tùy tiện được. Người ta gọi anh là “Mộ Dung ở phía nam và Kiều Phong ở phía bắc”, nên chỉ nói rằng cuốn sách ở bên anh ấy.", "talkname0", 1);
    Talk(109, "Anh họ tôi không hề nói dối, cuốn sách này quả thực đã nằm trong tay anh ấy.", "talkname109", 0);
    Talk(0, "Bạn có thể tin những gì cô Wang nói. Được rồi, tôi sẽ tới Băng đảng ăn xin và hỏi cuốn sách.", "talkname0", 1);
    Talk(51, "Không, không, cậu nên đến Thiếu Lâm trước.", "talkname51", 0);
    Talk(0, "làm thế nào để tôi nói điều này?", "talkname0", 1);
    Talk(51, "Nghĩ xem, bạn có thể đánh bại Kiều Phong đó không?", "talkname51", 0);
    Talk(0, "Đánh không lại cũng phải đánh, nếu không thì phải làm sao?", "talkname0", 1);
    Talk(51, "Tôi có cách khiến Kiều Phong ngoan ngoãn giao sách ra.", "talkname51", 0);
    Talk(0, "Tại sao anh ta lại ngoan ngoãn giao nó?", "talkname0", 1);
    Talk(51, "Bởi vì tôi biết một bí mật rất lớn về anh ấy, một bí mật có thể hủy hoại danh tiếng của anh ấy.", "talkname51", 0);
    Talk(0, "Vậy thì tại sao lại đến Thiếu Lâm trước?", "talkname0", 1);
    Talk(51, "Bởi vì tôi phải đến Thiếu Lâm Tự để lấy thứ gì đó trước đã.", "talkname51", 0);
    Talk(0, "Giống nhau cả thôi?", "talkname0", 1);
    Talk(51, "Đúng, thứ có thể đảo lộn thế giới võ thuật. Dù sao đi nữa, nếu bạn đi cùng tôi, tôi có thể giúp bạn lấy được cuốn sách một cách dễ dàng. Nếu không, bạn có đủ tự tin để tự mình đánh bại Qiao Feng không?", "talkname51", 0);
    Talk(0, "Tại sao bạn muốn giúp tôi?", "talkname0", 1);
    Talk(51, "Không có gì đâu, cá giúp nước và nước giúp cá. Mộ Dung tộc ta ta dân số ít, thế lực yếu, muốn xây dựng lại đất nước không phải là điều dễ dàng. Cơ hội duy nhất là thế giới hỗn loạn và thế giới võ thuật hỗn loạn. Và bạn có thể có được những gì bạn muốn từ nó.", "talkname51", 0);
    Talk(109, "Em ơi, đừng điên cuồng nghĩ đến việc khôi phục đất nước và gây hỗn loạn trên thế giới.", "talkname109", 0);
    Talk(51, "Câm miệng! Bạn cho rằng tại sao Mộ Dung Phục ta lại có chữ \"Phúc\"? Tại sao bạn cho rằng gia tộc Mộ Dung của ta đã lưu lạc qua nhiều thế hệ? Cái gì, bạn có muốn hợp tác với tôi không?", "talkname51", 0);
    ModifyEvent(-2, 5, -2, -2, 497, -1, -1, -2, -2, -2, -2, -2, -2);
    ModifyEvent(-2, -2, -2, -2, 494, -1, -1, -2, -2, -2, -2, -2, -2);
    ModifyEvent(-2, 2, -2, -2, 495, -1, -1, -2, -2, -2, -2, -2, -2);
    ModifyEvent(51, 14, -2, -2, 527, 531, -1, -2, -2, -2, -2, -2, -2);
    if AskJoin () == true then goto label1 end;
        Talk(0, "Ý định \"tốt\" của Thầy Mộ Dung đã được tôi hết lòng chấp nhận. Tôi vẫn có chút tự tin vào võ công của mình, tôi thà đấu với Kiều Đại Hạ một cách công khai và công bằng, còn hơn dùng thủ đoạn hèn hạ để có được bản sao của \"Dragon Babu\".", "talkname0", 1);
        Talk(51, "Hãy suy nghĩ lại.", "talkname51", 0);
        do return end;
::label1::
        Talk(0, "Được rồi, tôi sẽ cùng bạn đến Thiếu Lâm và vạch trần bí mật của Qiao Feng.", "talkname0", 1);
        if TeamIsFull() == false then goto label2 end;
            Talk(51, "Nhóm của bạn đã đầy đủ và tôi không thể tham gia.", "talkname51", 0);
            do return end;
::label2::
            DarkScence();
            jyx2_ReplaceSceneObject("", "NPC/慕容复", "");--慕容复
            ModifyEvent(-2, -2, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
            ModifyEvent(-2, 2, -2, -2, 495, -1, -1, -2, -2, -2, -2, -2, -2);
            LightScence();
            Join(51);
do return end;
