Talk(97, "Đứa trẻ này từ đâu đến, dám đột nhập vào đảo Thần Long của chúng ta mà không được phép.", "talkname97", 0);
Talk(0, "Đảo rồng? Nghe thì có vẻ khá khó nhưng lần sau tôi tự tin hơn thì nên làm.", "talkname0", 1);
Talk(97, "Nếu muốn rời đi, Thần Long Đảo không phải là để cho ngươi muốn đến rồi đi lúc nào cũng được.", "talkname97", 0);
Talk(0, "Đừng như thế! Thuyền của tôi có thể tùy ý mở ra và đi đến hòn đảo của bạn. Tôi muốn xem bạn có cuốn sách tôi đang tìm không, nhưng... tôi không nghĩ vậy... Xin lỗi...", "talkname0", 1);
Talk(97, "Quả nhiên là hắn tới trộm sách. Có người đang đến! Hãy nhanh chóng đưa anh ấy đi.", "talkname97", 0);
if TryBattle(94) == true then goto label0 end;
    Dead();
    do return end;
::label0::
    ModifyEvent(-2, 5, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
    ModifyEvent(-2, 6, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
    ModifyEvent(-2, 7, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
    ModifyEvent(-2, 8, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
    ModifyEvent(-2, 9, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
    ModifyEvent(-2, 10, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
    jyx2_ReplaceSceneObject("","NPC/神龙弟子5","");
    jyx2_ReplaceSceneObject("","NPC/神龙弟子6","");
    jyx2_ReplaceSceneObject("","NPC/神龙弟子7","");
    jyx2_ReplaceSceneObject("","NPC/神龙弟子8","");
    jyx2_ReplaceSceneObject("","NPC/神龙弟子9","");
    jyx2_ReplaceSceneObject("","NPC/神龙弟子10","");
    LightScence();
    Talk(0, "Không có nơi nào được tìm thấy ngay cả khi đi giày sắt và không cần nỗ lực để đến đó. Có thể ở đây có cuốn sách tôi đang tìm, bạn vào hỏi ông chủ của họ xem.", "talkname0", 1);
    AddRepute(1);
do return end;
