Talk(0, "Ở đây chắc chắn bạn là ông chủ, tôi nghe nói bạn có cuốn sách tôi đang tìm... Tôi không nghĩ bạn sẽ dễ dàng đưa nó cho tôi... Bạn nghĩ sao? Bạn sắp đánh nhau à?", "talkname0", 1);
Talk(71, "Gần đây tôi nghe nói có một thanh niên anh hùng từ Trung Quốc nổi lên, có lẽ là bạn! Những người có thể đột nhập vào giáo phái này chắc chắn sẽ gặp rất nhiều rắc rối.", "talkname71", 0);
Talk(0, "Bạn biết tôi mạnh mẽ đến mức nào, vậy bạn muốn tôi ra tay hay chỉ nên ngoan ngoãn giao cuốn sách ra.", "talkname0", 1);
Talk(71, "Bạn muốn cuốn sách "Con nai và cái vạc"! Thật tiếc là đã quá muộn.", "talkname71", 0);
Talk(0, "làm thế nào để tôi nói điều này?", "talkname0", 1);
Talk(71, "Nửa tháng trước, có một người tên Vi Tiểu Bảo lẻn vào đảo, nhân cơ hội đánh cắp cuốn sách này. Người này bản tính xảo quyệt, xảo trá, giáo phái phái đại quân bao vây trấn áp hắn nhiều lần, nhưng lần nào hắn cũng trốn thoát. Nếu anh hùng trẻ tuổi có thể giết được hắn, hắn đương nhiên sẽ có được cuốn sách.", "talkname71", 0);
Talk(0, "Khi thời điểm đến, bạn có đến lấy nó từ tay tôi lần nữa không?", "talkname0", 1);
Talk(71, "Nó đã bị anh hùng trẻ tuổi lấy đi, đương nhiên sẽ thuộc về anh hùng trẻ tuổi.", "talkname71", 0);
Talk(0, "Điều này có đúng không?", "talkname0", 1);
Talk(71, "Làm sao tôi có thể là người không giữ lời?", "talkname71", 0);
Talk(0, "Vậy bạn có biết nơi ở của anh ấy không?", "talkname0", 1);
Talk(71, "Người này luôn dâm đãng, tôi nghe nói gần đây anh ta đã đến Vân Nam. Không ngờ anh ta lại dám gây sự với người phụ nữ độc ác đó.", "talkname71", 0);
Talk(0, "Ý của người đứng đầu là...", "talkname0", 1);
Talk(71, "Vân Nam Ngũ Độc Phái.", "talkname71", 0);
Talk(0, "Tốt. Tôi thà gặp tên biến thái to lớn này còn hơn.", "talkname0", 1);
ModifyEvent(-2, -2, -2, -2, 610, -1, -1, -2, -2, -2, -2, -2, -2);
ModifyEvent(37, 5, 1, 1, 616, -1, -1, 6804, 6804, 6804, -2, -2, -2);
jyx2_ReplaceSceneObject("37","NPC/lanfenghuang","1");
ModifyEvent(37, 0, -2, -2, 613, -1, -1, -2, -2, -2, -2, -2, -2);
ModifyEvent(37, 1, -2, -2, 613, -1, -1, -2, -2, -2, -2, -2, -2);
ModifyEvent(37, 2, -2, -2, 613, -1, -1, -2, -2, -2, -2, -2, -2);
ModifyEvent(37, 3, -2, -2, 613, -1, -1, -2, -2, -2, -2, -2, -2);
ModifyEvent(37, 4, -2, -2, 613, -1, -1, -2, -2, -2, -2, -2, -2);
do return end;
