Talk(25, "Thiếu gia nóng lòng muốn gặp ta, có chuyện gì quan trọng vậy?", "talkname25", 0);
Talk(0, "Bạn có phải là người lãnh đạo? Không đời nào! Bạn còn trẻ quá, bạn cũng sử dụng "Oulet" à?", "talkname0", 1);
Talk(25, "Cô bé không hiểu được thiếu gia đang nói gì.", "talkname25", 0);
Talk(0, "Tôi đến đây lần này vì muốn hỏi thăm tung tích của một người nào đó từ người lãnh đạo.", "talkname0", 1);
Talk(25, "Thiếu gia muốn hỏi ai?", "talkname25", 0);
Talk(0, "Vi Tiểu Bảo.", "talkname0", 1);
Talk(25, "Sư phụ, ai nghe nói hắn ở đây?", "talkname25", 0);
Talk(0, "Lãnh đạo Hồng của Thần Long phái.", "talkname0", 1);
Talk(25, "khịt mũi! Hóa ra đó là tay sai của Giáo phái Shenlong. Nếu muốn biết tung tích của Ngụy tiên sinh, trước tiên hãy đánh bại tôi.", "talkname25", 0);
Talk(0, "Làm sao để lật trang nhanh như lật trang sách?", "talkname0", 1);
if TryBattle(98) == true then goto label0 end;
    Dead();
    do return end;
::label0::
    ModifyEvent(-2, -2, -2, -2, 617, -1, -1, -2, -2, -2, -2, -2, -2);
    ModifyEvent(-2, 0, -2, -2, 619, -1, -1, -2, -2, -2, -2, -2, -2);
    ModifyEvent(-2, 1, -2, -2, 619, -1, -1, -2, -2, -2, -2, -2, -2);
    ModifyEvent(-2, 2, -2, -2, 619, -1, -1, -2, -2, -2, -2, -2, -2);
    ModifyEvent(-2, 3, -2, -2, 619, -1, -1, -2, -2, -2, -2, -2, -2);
    ModifyEvent(-2, 4, -2, -2, 619, -1, -1, -2, -2, -2, -2, -2, -2);
    ModifyEvent(71, 3, -2, -2, 611, -1, -1, -2, -2, -2, -2, -2, -2);
    LightScence();
    Talk(0, "Tại sao cô gái lại hành động dễ dàng như vậy, nếu cô gái không muốn nói cho tôi biết, tôi cũng sẽ không làm khó.", "talkname0", 1);
    Talk(25, "Giết hay chặt hắn thành từng mảnh là tùy bạn, đừng kiêu ngạo như vậy.", "talkname25", 0);
    Talk(0, "Tốt! Có phải tất cả phụ nữ Miêu đều nóng tính như vậy không? Tôi chỉ muốn hỏi Vi Tiểu Bảo tung tích của "Hươu và vạc".", "talkname0", 1);
    Talk(25, "Con chó cái tên He đâu rồi? Tôi muốn sử dụng sức mạnh của Giáo phái Thần Long để giành lại vị trí thủ lĩnh, nhưng tôi không dám ra ngoài.", "talkname25", 0);
    Talk(0, "Bạn đang nói về cái gì vậy, vị trí của người lãnh đạo là gì.", "talkname0", 1);
    Talk(25, "Chẳng phải ngươi đã giúp tên phản bội Hà Thiết Thủ đến chiếm lấy vị trí thủ lĩnh của ta sao?", "talkname25", 0);
    Talk(0, "KHÔNG! Tôi đang tìm cuốn sách "Con nai và chiếc vạc", Hồng lãnh đạo nói với tôi rằng nó đã bị Vi Tiểu Bảo đánh cắp và hắn đang trốn ở đây với bạn.", "talkname0", 1);
    Talk(25, "Ông Ngụy, đúng là ông ta đến Đảo Thần Long để trộm sách, nhưng cuốn "Bốn mươi hai chương" chứ không phải cuốn "Con nai và chiếc vạc" mà ông nhắc tới.", "talkname25", 0);
    Talk(0, "Thật sự, còn Vi Tiểu Bảo và những người khác thì sao?", "talkname0", 1);
    Talk(25, "Anh ta! Ông cùng bảy người vợ xinh đẹp cùng nhau ra đi hạnh phúc. Tôi cũng không biết anh ấy đã đi đâu.", "talkname25", 0);
    Talk(0, "Tại sao anh Hồng lại nói dối tôi?", "talkname0", 1);
    Talk(25, "Bạn rất ngu ngốc! Tôi không biết liệu mình có bị lợi dụng hay không. Hắn muốn dùng tay của bạn để giết ông Ngụy và lấy lại "Bốn mươi hai chương". Việc còn lại là giết tôi để He Tieshou, một kẻ phản bội tôn giáo của chúng tôi, trở thành người lãnh đạo và kiểm soát tôi.", "talkname25", 0);
    Talk(0, "Mẹ kiếp, ngươi dám lừa gạt tình cảm của ta, ta phải tính sổ với hắn.", "talkname0", 1);
    Talk(25, "Tiểu cô nương vừa rồi cùng thiếu gia cãi nhau vô lý, thật xin lỗi. Nếu thiếu gia gặp khó khăn, tôi, Phượng Hoàng Xanh, sẵn sàng ra tay giúp đỡ.", "talkname25", 0);
    Talk(0, "Dù ở đâu thì tôi cũng đã sai.", "talkname0", 1);
    Talk(25, "Cô bé rất ngưỡng mộ võ công và tính cách của thiếu gia, cô rất muốn cùng thiếu gia du hành khắp thế giới.", "talkname25", 0);
    Talk(0, "＜Phụ nữ Miêu rất táo bạo và thẳng thắn trong lời nói. ＞", "talkname0", 1);
    AddRepute(1);
    ChangeMMapMusic(3);
    if AskJoin () == true then goto label1 end;
        Talk(0, "Cô gái ân cần tiếp nhận, nhưng người đàn ông liều lĩnh tiếp theo thực sự không dám trì hoãn tuổi thanh xuân của cô gái.", "talkname0", 1);
        do return end;
::label1::
        if TeamIsFull() == false then goto label2 end;
            Talk(25, "Nhóm của bạn đã đầy đủ và tôi không thể tham gia.", "talkname25", 0);
            do return end;
::label2::
            Talk(0, "Thật sự là vinh dự cho tôi khi có một người phụ nữ xinh đẹp đi cùng tôi đến tận cùng thế giới.", "talkname0", 1);
            DarkScence();
            jyx2_ReplaceSceneObject("", "NPC/lanfenghuang", "");--蓝凤凰加入
            ModifyEvent(-2, -2, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
            LightScence();
            Join(25);
do return end;
