Talk(0, "Nhìn cách ăn mặc của bạn có vẻ bạn không phải là người Hán?", "talkname0", 1);
Talk(87, "Vậy nếu tôi không phải là Han thì sao? Người Miêu chúng tôi không vô tâm như người Hán các bạn.", "talkname87", 0);
Talk(0, "Không có lương tâm?", "talkname0", 1);
Talk(87, "Người Hàn các ngươi chỉ lừa dối tình cảm của người khác rồi bỏ đi.", "talkname87", 0);
Talk(0, "Ai đã nói thế! Thiếu gia, tôi là người đàn ông si tình nhất trên thế giới.", "talkname0", 1);
Talk(87, "Vâng? Tôi thấy bạn trông khá ổn và khá thành thật...", "talkname87", 0);
Talk(0, "Các bạn thực sự hiểu tôi.", "talkname0", 1);
Talk(87, "Được rồi các anh em hãy bắt thằng nhóc này và trình diện cho thủ lĩnh. Kể từ khi người tên Ngụy bỏ trốn, thủ lĩnh đã buồn bã một thời gian, vậy hãy để đứa trẻ này làm cho thủ lĩnh vui vẻ.", "talkname87", 0);
Talk(0, "Không, không, tôi còn có rất nhiều việc quan trọng phải làm, tôi không thể ở lại đây với lãnh đạo của anh được. Huống chi, ta còn không biết ngươi sẽ ngược đãi ta như thế nào!", "talkname0", 1);
if TryBattle(96) == true then goto label0 end;
    Dead();
    do return end;
::label0::
    ModifyEvent(-2, 0, -2, -2, 615, -1, -1, -2, -2, -2, -2, -2, -2);
    ModifyEvent(-2, 1, -2, -2, 615, -1, -1, -2, -2, -2, -2, -2, -2);
    ModifyEvent(-2, 2, -2, -2, 615, -1, -1, -2, -2, -2, -2, -2, -2);
    ModifyEvent(-2, 3, -2, -2, 615, -1, -1, -2, -2, -2, -2, -2, -2);
    ModifyEvent(-2, 4, -2, -2, 615, -1, -1, -2, -2, -2, -2, -2, -2);
    LightScence();
    AddRepute(1);
do return end;
