if UseItem(190) == true then goto label0 end;
    do return end;
::label0::
    AddItemWithoutHint(190, -1);
    Talk(13, "Chạm vào hình dáng này, hình như là Thiết Hỏa Lệnh của Minh Giáo của ta?", "talkname13", 0);
    Talk(0, "Người cao tuổi có lẽ là Xie Xun, Vua sư tử Golden Retriever. Ta đã tìm kiếm tiền bối của ta đã lâu, các huynh đệ Minh Giáo của ngươi cũng đang tìm kiếm ngươi. Nếu không quay lại, Mingjiao sẽ tan nát.", "talkname0", 1);
    Talk(13, "Bạn nói gì! Chuyện gì đã xảy ra với anh em Mingjiao của tôi?", "talkname13", 0);
    Talk(0, "Hiện tại không có việc gì, sáu đại giáo phái bao vây Quảng Minh Đỉnh nguy hiểm vừa mới giải quyết, trong tương lai gần người của sáu đại giáo phái sẽ không bao giờ dám gây chuyện. Tuy nhiên, trong môn phái không có người đứng đầu, cũng không có bên nào tin tưởng đối phương, e rằng thời gian trôi qua, người của Minh giáo sẽ lợi dụng tình thế. Chi tiết sự việc xảy ra như sau...", "talkname0", 1);
    Talk(13, "Cheng Kun, tên trộm già này, không chỉ có mối hận thù sâu sắc với tôi, mà còn là kẻ thù lớn nhất của Ming Giáo của tôi, tôi phải giết anh ta. Tôi nghĩ rằng tôi có thể giết anh ta sau khi tôi lấy con dao diệt rồng chỉ huy thế giới này và tìm ra bí mật trong con dao. Nhưng sau hơn mười năm nghiên cứu, tôi vẫn chưa thể hiểu được sự kỳ diệu và bí ẩn của con dao này. Tốt! Nếu tôi không mở khóa được bí mật của thanh kiếm này, tôi sẽ không rời khỏi Đảo Lửa và Băng.", "talkname13", 0);
    Talk(0, "Tiền bối đừng lo lắng như vậy, tốt nhất là theo ta về Trung Nguyên trước, chúng ta cùng nhau nghĩ biện pháp.", "talkname0", 1);
    Talk(13, "Đừng nói nữa và đi đi. Nếu không giết Trình Khôn, ta sẽ không trở lại Minh Giao.", "talkname13", 0);
    ModifyEvent(-2, -2, -2, -2, -2, 65, -2, -2, -2, -2, -2, -2, -2);
    ModifyEvent(9, 0, 0, 0, -1, -1, 91, -1, -1, -1, -2, -2, -2);
    ModifyEvent(9, 1, 1, 1, -1, -1, -1, 5296, 5296, 5296, -2, -2, -2);
    ModifyEvent(9, 2, 1, 1, -1, -1, -1, 6092, 6092, 6092, -2, -2, -2);
    ModifyEvent(9, 3, 1, 1, -1, -1, -1, 6788, 6788, 6788, -2, -2, -2);
    ModifyEvent(9, 4, 1, 1, -1, -1, -1, 5892, 5892, 5892, -2, -2, -2);
    jyx2_ReplaceSceneObject("9", "NPC/成昆喽喽1", "1");
    jyx2_ReplaceSceneObject("9", "NPC/成昆喽喽2", "1");
    jyx2_ReplaceSceneObject("9", "NPC/成昆喽喽3", "1");
    jyx2_ReplaceSceneObject("9", "NPC/成昆", "1");
do return end;
