if InTeam(9) == true then goto label0 end;
    Talk(0, "Tiền bối, anh ổn chứ?", "talkname0", 1);
    Talk(13, "khịt mũi! Bạn đang làm gì nữa vậy?", "talkname13", 0);
    do return end;
::label0::
    -- jyx2_ReplaceSceneObject("", "NPC/zhangwuji", "1"); 
    Talk(9, "Cha nuôi, đứa trẻ vô cùng bất hiếu, không thể đến gặp ông càng sớm càng tốt, điều này khiến cha nuôi vô cùng đau khổ.", "talkname9", 1);
    Talk(13, "Bạn...bạn đã nói gì vậy?", "talkname13", 0);
    Talk(9, "Đứa trẻ là Vô Kỵ.", "talkname9", 1);
    Talk(13, "Bạn...bạn đã nói gì vậy?", "talkname13", 0);
    Talk(9, "Nghệ thuật đấm bốc nằm ở việc tập trung tinh thần, nhằm giành chiến thắng đầu tiên,...", "talkname9", 1);
    Talk(13, "Đây... đây chẳng phải là công thức mà ngày xưa tôi đã dạy cho đứa con Wuji của mình sao? Bạn có thực sự là đứa trẻ Wuji của tôi?", "talkname13", 0);
    Talk(9, "Cha nuôi! Cha nuôi!", "talkname9", 1);
    Talk(13, "Chúa mở mắt cho bạn! Chúa mở mắt cho bạn! Tiểu tử Vô Kỵ, mấy năm nay ngươi sống thế nào?", "talkname13", 0);
    Talk(9, "Đứa trẻ đang làm tốt. Hôm nay nhờ có người anh lớn này mà cha con chúng ta mới được đoàn tụ. Cha nuôi, xin hãy quay lại Trung Địa với chúng tôi.", "talkname9", 1);
    Talk(13, "Bạn đang sống một cuộc sống tốt đẹp và cha nuôi của bạn sẽ rất hạnh phúc. Cha nuôi còn phải ở lại đây suy nghĩ nên đối phó Trình Khôn như thế nào, ngươi có thể đi. Hãy nhớ rằng, khi du hành trên thế giới, bạn phải đề phòng những kẻ hung ác, thậm chí là chủ nhân hoặc người anh em kết nghĩa của chính mình.", "talkname13", 0);
    ModifyEvent(-2, -2, -2, -2, 64, -2, -2, -2, -2, -2, -2, -2, -2);
    -- jyx2_ReplaceSceneObject("", "NPC/zhangwuji", ""); 
    AddEthics(3);
do return end;
