Talk(54, "Yuan sống ẩn dật ở nước ngoài, ngày nay thực sự rất hiếm khi có du khách đến thăm anh.", "talkname54", 0);
Talk(0, "Anh Yuan sống một mình ở nước ngoài, anh có muốn tập trung luyện tập võ thuật không?", "talkname0", 1);
Talk(54, "Yuan không muốn vướng vào những bất bình đúng sai nữa.", "talkname54", 0);
Talk(0, "Đây là lần đầu tiên tôi bước vào thế giới võ thuật, tuy cảm thấy thế giới võ lâm thăng trầm, lòng người khó đoán nhưng tôi vẫn phải trải qua trải nghiệm này. Như người ta thường nói: “Khi bạn ở trên đấu trường, bạn không thể tự giúp mình”.", "talkname0", 1);
Talk(54, "Chẳng phải ngươi vẫn còn nhìn qua tất cả sao? Võ công, danh lợi, ngươi tranh đấu vì cái gì?", "talkname54", 0);
Talk(0, "Người em quả thực không còn cách nào khác ngoài việc chăm chỉ trong giới võ thuật. Bạn nói đúng, tôi muốn theo đuổi võ thuật cao hơn, và tôi muốn đánh bại các anh hùng trên thế giới và giành được vị trí thủ lĩnh của liên minh võ thuật. Nhưng tất cả những điều này chỉ nhằm đưa tôi ra khỏi đây và trở về nơi tôi thuộc về. Tốt! Anh Yuan có thể không hiểu những gì tôi đang đọc, tôi thật thô lỗ.", "talkname0", 1);
Talk(54, "Có vẻ như bạn đang gặp một số khó khăn phải không?", "talkname54", 0);
Talk(0, "Tôi tưởng mình là người may mắn khi có cơ hội chơi trò chơi thực tế nhất này nhưng không ngờ nó lại khó đến vậy. Tôi thực sự muốn về nhà bây giờ.", "talkname0", 1);
Talk(54, "Mặc dù tôi không hiểu lắm câu hỏi của bạn, nhưng khi gặp khó khăn, người trẻ làm sao có thể chán nản, tôi nghĩ khi đó mình là một chú bê con mới sinh không sợ hổ, trải qua bao khó khăn mới sống sót.", "talkname54", 0);
Talk(0, "Bằng cách này, Anh Yuan cũng đã ở đây.", "talkname0", 1);
Talk(54, "Vâng, đừng mất lòng. Hãy nhớ rằng, ở đâu có ý chí, ở đó có con đường.", "talkname54", 0);
Talk(0, "Sau khi nghe anh Yuan nói, tôi cảm thấy dễ chịu hơn nhiều. Tôi phải nhanh chóng vui lên và tìm kiếm \"Cuốn sách Mười bốn ngày\".", "talkname0", 1);
Talk(54, "Hóa ra đây chính là khó khăn mà bạn đề cập, quả thực đây không phải là chuyện dễ dàng.", "talkname54", 0);
Talk(0, "Nghe giọng điệu của Viên Anh, hình như anh ta có manh mối gì đó?", "talkname0", 1);
Talk(54, "Đúng, một trong những cuốn sách, \"Blue Blood Sword\", có liên quan đến tôi.", "talkname54", 0);
Talk(0, "Vậy thì hãy nhờ anh Yuan giúp đỡ.", "talkname0", 1);
Talk(54, "Không, giới trẻ ngày nay có muốn nhận được thứ gì đó mà không mất gì không? Phải dựa vào nỗ lực của chính mình thì quả ngọt mới có được.", "talkname54", 0);
Talk(0, "Đúng. Đây là điều anh Yuan đã dạy.", "talkname0", 1);
Talk(54, "Nếu bạn muốn có được cuốn sách này, bạn phải vượt qua ba bài kiểm tra.", "talkname54", 0);
Talk(0, "Ba bài kiểm tra?", "talkname0", 1);
Talk(54, "Đúng. Đầu tiên là thử thách “khôn ngoan”. Có một hang động rất ẩn gần Hoa Sơn và bạn phải tìm ra nó. Thứ hai là thử thách “dũng cảm”. Hang động này kỳ thực chính là nơi Kim Xà Nhân sống ẩn dật, trong đá có một thanh Kim Xà Kiếm cắm vào, phải có đủ lực mới có thể kéo nó ra. Con đường thứ ba là thử thách lòng nhân từ. Sau khi ngươi rút ra Kim Xà Kiếm trở lại với ta, ta sẽ nhìn thành tích của ngươi trong thiên hạ, nếu ngươi có thể đi đúng đường, ta sẽ tặng ngươi cuốn sách \"Blue Blood Sword\". Hãy tiếp tục.", "talkname54", 0);
ModifyEvent(-2, -2, -2, -2, 636, -1, -1, -2, -2, -2, -2, -2, -2);
ChangeMMapMusic(3);
do return end;
