Talk(72, "Chàng trai trẻ, cậu đến đây để trú ẩn trong Perak Hall của tôi phải không?", "talkname72", 0);
Talk(0, "Hội trường Perak? Đây được gọi là Hội trường Perak. Bạn có phải là một nghệ sĩ múa rối?", "talkname0", 1);
Talk(72, "Bạn đang nói vớ vẩn gì vậy! Bạn thậm chí còn không biết Perak Hall của tôi nắm giữ vị trí nào trên thế giới. Vậy bạn nên biết về "Kong Bala", cao thủ của Perak Hall, người đã gây chấn động trong giới võ thuật và chấn động mọi tôn giáo.", "talkname72", 0);
Talk(0, ""Kong Bala"! Đó không phải là một tên xã hội đen sao? Anh là người xấu phải không?", "talkname0", 1);
Talk(72, "Nói nhảm, Kong Bala ta sao có thể là người xấu, đừng nói nhảm, sẽ khiến ta không thu được đệ tử.", "talkname72", 0);
Talk(0, "Tôi không nói vớ vẩn, nếu không thì tại sao cả phòng chỉ có bạn, những người khác đã bị đưa đi kỷ luật chưa?", "talkname0", 1);
Talk(72, "Đó là bởi vì tôi chưa tìm được người phù hợp để quảng bá những lời dạy của Perak Hall của tôi, nếu không Perak Hall của tôi sẽ quá đông đúc.", "talkname72", 0);
Talk(0, "Chẳng trách sau này trên hòn đảo Đài Loan của tôi sẽ có rất nhiều “anh em” như vậy, một số đang chơi bóng, một số đang chơi “cầu thủ bóng”.", "talkname0", 1);
Talk(72, "Bạn đang nói líu lưỡi phải không? Ừm! Có vẻ như bạn rất có tài hùng biện và rất thích hợp làm đại sứ cho Perak Hall của tôi. Hãy làm thế này nhé. Tôi sẽ trao cho bạn vũ khí mạnh nhất của Thunderbolt Hall của tôi, "Thunderbolt Bullet", bạn có thể mang nó ra thế giới để thể hiện sức mạnh của mình và cho bạn bè trên đường biết Thunderbolt Hall của tôi mạnh đến mức nào.", "talkname72", 0);
Talk(0, ""Sấm sét"?", "talkname0", 1);
Talk(72, "Đúng vậy, viên đạn sét này là một loại vũ khí ẩn độc đáo do Thunderbolt Hall của tôi phát triển, nó được chế tạo từ "diêm tiêu" và cực kỳ mạnh mẽ. Tôi có một ít ở đây, hãy lấy chúng. Ngoài ra còn có “Sách bí mật sấm sét” ghi lại cách chế tạo đạn sét và giới thiệu về các loại vũ khí giấu kín thông thường, bạn cũng nên mang theo. Nhưng hãy nhớ rằng, bạn cần muối tiêu để tạo ra tiếng sét.", "talkname72", 0);
Talk(0, "Được rồi, đưa nó cho tôi nhanh lên. Với điều này, bạn có thể đánh bại kẻ thù ngay cả khi bạn không mạnh về võ thuật.", "talkname0", 1);
Talk(72, "Đợi một chút. Tôi nhớ ra một điều, tôi không thể đưa cái này cho bạn được.", "talkname72", 0);
Talk(0, "Tại sao?", "talkname0", 1);
Talk(72, "Tôi gần như quên mất lời giải thích của cha tôi, bố tôi bảo tôi hãy để chuyện này cho người thừa kế của "anh Jin". Bởi vì người này ngay từ đầu chắc chắn không có võ công tốt, cho nên hắn cần phải dựa vào những viên đạn sấm sét từ Sảnh Thunderbolt của ta để trợ giúp.", "talkname72", 0);
Talk(0, "Bố của bạn biết Mr. vàng?", "talkname0", 1);
Talk(72, "Có phải biệt danh của anh ấy là "Sương mù"? Cha tôi chưa bao giờ đề cập đến điều này. Nhưng theo bố tôi, mối quan hệ của họ khá tốt.", "talkname72", 0);
Talk(0, "Bạn có biết về "Sách Mười Bốn Ngày" không? Hay còn điều gì khác về anh Jin?", "talkname0", 1);
Talk(72, "Cha tôi không nói nhiều với tôi, ngoại trừ việc sau này hậu duệ của ông Jin có thể sẽ đến và nhờ tôi giúp đỡ ông ấy... Nhân tiện, tại sao bạn lại hỏi những câu hỏi này? Nó có thể là...", "talkname72", 0);
Talk(0, "Vâng, tôi là hậu duệ đó.", "talkname0", 1);
Talk(72, "Thật sự! Thật tuyệt. Vậy tôi có thể cho bạn hai thứ này.", "talkname72", 0);
Talk(0, "Cảm ơn Đại sư Khổng.", "talkname0", 1);
Talk(72, "Nhân tiện, trong nhà còn có hai thứ khác, nên hãy mang theo luôn. Nó còn là loại vật có tác dụng bồi bổ tinh thần, phục hồi thể lực, cũng là sản phẩm nổi tiếng của hòn đảo này, được mệnh danh là “trầu trầu”.", "talkname72", 0);
Talk(0, "Ôi chúa ơi!", "talkname0", 1);
Talk(72, "Một thứ nữa là chiếc "áo khoác da" tôi từng mặc, có chức năng phòng thủ. Nhưng dạo này nóng quá, tôi không có nhu cầu nên để lại cho bạn.", "talkname72", 0);
Talk(0, "＜Mặc đồ da và ăn trầu! Đó thực sự là một “Kong Bala” tiêu chuẩn! ＞", "talkname0", 1);
Talk(72, "Nếu trong nhà còn cần thứ gì khác, bạn có thể thoải mái lấy nó, không sao cả. Sau này nếu gặp khó khăn gì hãy quay lại với tôi, cho dù tôi không giúp được gì thì tôi cũng sẽ gọi một nhóm anh em đến giúp đỡ. Tuy nhiên, tôi phải dựa vào bạn để nâng cao danh tiếng cho Perak Hall của tôi trước.", "talkname72", 0);
Talk(0, "Tôi sẽ. Vậy thì tôi sẽ nghỉ phép.", "talkname0", 1);
Talk(72, "Đi chậm.", "talkname72", 0);
--Talk(0, "Nếu trong nhà còn cần thứ gì khác thì cứ thoải mái lấy, không sao cả.", "talkname0", 1);
AddItem(101, 10);
AddItem(89, 1);
AddItem(163, 1);
ModifyEvent(-2, -2, -2, -2, 679, 686, -1, -2, -2, -2, -2, -2, -2);
do return end;
