if UseItem(143) == true then goto label0 end;
    do return end;
::label0::
    AddItemWithoutHint(143, -1);
    Talk(72, "Đây... đây... đây là \"Võ trượng\"! Bạn...bạn đã trở thành thủ lĩnh của liên minh võ thuật! ha! ha! ha! Bạn xứng đáng trở thành đệ tử của Perak Hall của tôi. Hôm nay cậu đến đây để đưa cho tôi vương trượng phải không?", "talkname72", 0);
    Talk(0, "đưa cho bạn? Tôi đã phải trải qua rất nhiều công việc khó khăn để có được thứ này. Bạn đang khoe khoang phải không?", "talkname0", 1);
    Talk(72, "Làm sao? Bạn không muốn gửi nó cho tôi à? Giữ nó có ích gì?", "talkname72", 0);
    Talk(0, "Tại sao nó vô dụng? Cây trượng thần này có liên quan đến hạnh phúc tương lai của tôi. Tôi vẫn phải dựa vào nó để tìm ra \"Ngôi đền\" phải không?", "talkname0", 1);
    Talk(72, "\"Ngôi đền\"? Đây là tôi!", "talkname72", 0);
    Talk(0, "Cái gì! Đây có phải là \"Đền\" không? Không phải bạn nói nó tên là Perak Hall sao?", "talkname0", 1);
    Talk(72, "Khi cha tôi còn là chủ của nhà thờ, nó được gọi là Nhà thờ Thánh. Nhưng sau này tôi kế thừa nó, nó được gọi là \"Perak Hall\". Bởi vì tôi nghĩ \"Perak Hall\" nghe có vẻ độc đoán hơn.", "talkname72", 0);
    Talk(0, "Vậy bạn có biết cách thoát khỏi \"đây\" không? Ý tôi là……", "talkname0", 1);
    Talk(72, "Không dễ để rời đi, chỉ cần bước ra khỏi cửa trước.", "talkname72", 0);
    Talk(0, "Khi tôi nói \"ở đây\" tôi không thực sự có ý ở đây...", "talkname0", 1);
    Talk(72, "Bạn không định đi ra ngoài bằng cửa trước à? ...Có một lối ra khác, ngay dưới chân chúng ta. Nhưng...nhưng bố tôi dặn tôi không được nói cho người khác biết. Nhưng...nếu ngài sẵn lòng trao cho tôi quyền trượng võ thuật...", "talkname72", 0);
    Talk(0, "Đây…đây là biểu tượng của thủ lĩnh võ thuật. Ban đầu tôi muốn mang nó về làm kỷ niệm. Chắc chắn là bạn đã nói dối tôi! ...<Nhưng nhìn vào vẻ ngoài bí ẩn của anh ấy, có lẽ anh ấy thực sự có thể khiến tôi quay trở lại. ＞Được rồi! Chỉ cần đưa nó cho bạn.", "talkname0", 1);
    Talk(72, "ha! ha! Tôi nghĩ tôi, Kong Bala, mạnh mẽ biết bao, ngồi ở nhà không ra ngoài lại có thể trở thành “Võ sư” mà mọi người mơ ước. Từ nay trở đi, khi ta ra lệnh cho thiên hạ, ai dám trái lệnh?", "talkname72", 0);
    Talk(0, "Này, bạn đã vui vẻ xong rồi. Bạn có thể cho tôi biết lối ra còn lại ở đâu không?", "talkname0", 1);
    Talk(72, "Được rồi, một câu. “Ngay dưới chân cả hai chúng ta.” Và đây chính là chìa khóa của “Ngôi đền”. lấy nó.", "talkname72", 0);
    AddItem(164, 1);
    ModifyEvent(-2, -2, -2, -2, 687, -1, -1, -2, -2, -2, -2, -2, -2);
do return end;
