Talk(0, "CHÀO! Bạn tên gì và bạn đang làm gì ẩn náu trong núi một mình?", "talkname0", 1);
Talk(9, "Tôi tên là Trương Vô Kỵ, sao cậu cũng ở đây?", "talkname9", 0);
Talk(0, "Tôi tình cờ tìm thấy nơi này. Này, bạn có bị tự kỷ không? Hay bạn đang trốn một mình trong núi luyện tập phép thuật?", "talkname0", 1);
Talk(9, "Tự kỷ? Đó là bệnh gì? Sách y của Bác Hồ không hề đề cập đến căn bệnh này. Trên thực tế, tôi đã bị trúng độc bởi chất độc lạnh của Huyền Minh Thần Chưởng, một căn bệnh nan y.", "talkname9", 0);
Talk(0, "Nhưng tôi thấy bạn trông rất ổn và không giống người sắp chết.", "talkname0", 1);
Talk(9, "Tôi cũng thấy lạ nhỉ? Nói một cách logic, lẽ ra tôi đã chết từ vài năm trước, nhưng bây giờ tôi sẽ không còn bị bệnh nữa.", "talkname9", 0);
Talk(0, "Bạn đã uống thuốc tiên ma thuật chưa?", "talkname0", 1);
Talk(9, "Khoảng bốn năm năm trước, sau khi rời khỏi Thung lũng Bướm, tôi vô tình phát hiện ra thiên đường này, nghĩ rằng chết ở đây sẽ sướng lắm nên quyết định ở lại đây chờ chết. Mấy năm trước tình cờ cứu được một con vượn trắng lớn, trong bụng nó tìm được một cuốn kinh, hình như là sách rèn luyện nội lực, muốn rảnh rỗi nên bắt đầu tu luyện theo đó. Ngoài ra, một số loại trái cây và cá trắng ở đây khiến tôi cảm thấy sảng khoái hơn sau khi ăn. Phải chăng những cuộc gặp gỡ đó đã giúp tôi sống sót đến tận bây giờ?", "talkname9", 0);
Talk(0, "Theo tôi, bạn không những không thể chết mà còn luyện được võ công vô song, tôi nghĩ đây chắc hẳn là một phép màu đối với bạn. Bạn đã ở đây lâu như vậy, bạn không muốn ra ngoài đi dạo sao?", "talkname0", 1);
Talk(9, "Tôi tưởng mình sắp chết nên ở lại đây suốt, nhưng sau những gì bạn nói, giờ tôi muốn ra ngoài. Tôi muốn quay lại núi Võ Đang để gặp sư phụ vĩ đại của mình, đồng thời cũng để tìm cha nuôi của mình.", "talkname9", 0);
Talk(0, "Cha nuôi của bạn?", "talkname0", 1);
Talk(9, "Đúng. Cha nuôi của tôi là Xie Xun, vua sư tử chó vàng, ông bị mù và sống một mình trên một hòn đảo hoang.", "talkname9", 0);
ModifyEvent(-2, -2, -2, -2, 75, 71, -2, -2, -2, -2, -2, -2, -2);
do return end;
