Talk(14, "Chàng trai, cậu không tệ chút nào!", "talkname14", 0);
Talk(10, "Vua Dơi, đừng thô lỗ. Tất cả các đệ tử Mingjiao đều cảm ơn vì lòng tốt to lớn của bạn trong việc bảo vệ và cứu sống!", "talkname10", 0);
Talk(0, "Đừng nói như vậy, đó là việc mà những người ở thế hệ chúng ta nên làm. Hơn nữa, lần này cũng chính vì sự liều lĩnh của tôi mà em đã rơi vào một trận chiến cay đắng.", "talkname0", 1);
Talk(12, "Ở đâu, chúng tôi không hỏi rõ.", "talkname12", 0);
Talk(14, "Đừng lịch sự thế. Được rồi, mọi người hãy nghe tôi nói, điều tôi nói là võ công của vị anh hùng trẻ tuổi này là vô song và chính nghĩa của anh ấy là vô song, anh ấy là ân nhân lớn cho giáo phái của chúng tôi sẽ tồn tại mãi mãi. Chúng tôi ủng hộ ông ấy với tư cách là nhà lãnh đạo thứ 34 của tôn giáo chúng tôi. Thà anh ấy làm trưởng nhóm còn hơn để bạn làm trưởng nhóm, Yang Zuoshi, bạn có nghĩ vậy không?", "talkname14", 0);
Talk(11, "Đúng! Người anh hùng trẻ tuổi này có thể làm thủ lĩnh của chúng tôi tốt hơn nhiều so với bạn, Wei Yixiao.", "talkname11", 0);
Talk(14, "Bạn……", "talkname14", 0);
Talk(10, "Hai người đừng cãi nhau nữa, xấu hổ quá.", "talkname10", 0);
Talk(0, "Không, không, mặc dù tôi luôn mơ ước trở thành người lãnh đạo. Nhưng tôi vẫn còn việc quan trọng phải làm và tôi đến từ một thế giới khác với bạn, vì vậy tốt nhất bạn nên tìm người khác.", "talkname0", 1);
Talk(10, "Nếu anh tiếp tục từ chối, anh hùng trẻ tuổi, chúng ta, Minh giáo, có lẽ sẽ không ngừng tranh cãi về vấn đề này và bị chia cắt, sau đó sẽ bị các giáo phái khác vây hãm, dẫn đến diệt vong.", "talkname10", 0);
Talk(0, "Ở đây tôi có lá thư tuyệt mệnh của Phong Dương sư phụ, trong đó đề cập đến Pháp Vương Tuân Hiệp nên tạm thời làm người lãnh đạo. Tôi nghĩ bạn nên tìm anh ấy trước rồi mới nói chuyện.", "talkname0", 1);
Talk(10, "Ồ! Đó là sự thật, thôi nào! Lập tức ra lệnh đi xuống, dốc toàn lực tìm kiếm Pháp Vương Tạ.", "talkname10", 0);
Talk(0, "Còn một điều nữa dành cho bạn, có cuốn sách tên là \"Truyền thuyết về Thiên Long Kiếm\" trong giáo phái Ming của bạn không? Bạn có thể cho tôi mượn nó được không?", "talkname0", 1);
Talk(10, "một số. Dương thủ lĩnh từng nói với ta, trong giáo phái của chúng ta có một cuốn sách kỳ lạ, là bảo vật của Minh giáo chúng ta, đã được các thủ lĩnh giáo phái truyền từ đời này sang đời khác.", "talkname10", 0);
Talk(0, "Vâng? thực sự có. Huangtian đã trả hết công sức của mình và chiến đấu rất nhiều trận, và cuối cùng tôi đã tìm thấy nó.", "talkname0", 1);
Talk(10, "Tuy nhiên, do sự biến mất đột ngột của Dương Giáo chủ nên không ai biết tung tích của nó.", "talkname10", 0);
Talk(12, "Anh hùng trẻ tuổi yên tâm, sau khi tìm được Tạ Vương và tổ chức việc học hành, chúng ta sẽ cố gắng hết sức để tìm kiếm tung tích của cuốn sách này. Nếu có tin tức gì, ta nhất định sẽ báo cho thiếu niên anh hùng.", "talkname12", 0);
Talk(0, "Vâng đó là tất cả. Khi nào có thời gian tôi cũng sẽ giúp anh tìm Tạ tiền bối, bây giờ tôi sẽ nói lời tạm biệt.", "talkname0", 1);
Talk(10, "Ở đây có một Thẻ Ngọn lửa Thiết, là một thẻ bài của Minh giáo của tôi. Anh hùng trẻ tuổi đi trên sông hồ, nếu bạn gặp khó khăn và cần sự giúp đỡ từ Mingjiao của chúng tôi, bạn chỉ cần đưa ra Thẻ Ngọn lửa Thiết giáp này, và tất cả các thành viên Mingjiao của chúng tôi chắc chắn sẽ giúp đỡ.", "talkname10", 0);
ModifyEvent(-2, 6, -2, -2, 88, -1, -1, -2, -2, -2, -2, -2, -2);--by fanyu|启动脚本88-改变对话。场景11-6
do return end;
