Talk(16, "Hãy ra khỏi đây nhanh chóng.", "talkname16", 0);
if InTeam(9) == true then goto label0 end;
    do return end;
::label0::
	jyx2_ReplaceSceneObject("", "NPC/张无忌", "1"); 
    Talk(9, "Chú Hồ, chú quên cháu rồi à? Ta là Vô Kỵ, Võ Đang Trương Thúy Sơn hậu nhân, Trương Vô Kỵ!", "talkname9", 1);
    Talk(16, "Bạn là Wuji! Bạn đã lớn như vậy chưa? Trông bạn ổn đấy, bạn đã khỏi cơn độc lạnh chưa?", "talkname16", 0);
    Talk(9, "Đúng! Cuộc phiêu lưu của tôi ở dãy núi Côn Luân đã chữa khỏi mọi chất độc lạnh trong cơ thể tôi.", "talkname9", 1);
    Talk(16, "Điều đó tốt, điều đó tốt.", "talkname16", 0);
    Talk(9, "Vợ thầy đâu? Tại sao bạn không nhìn thấy cô ấy? Cô ấy ổn chứ?", "talkname9", 1);
    Talk(16, "Vợ của chủ nhân ngươi...bà...bà ta bị bà Kim Hoa bắt đi.", "talkname16", 0);
    Talk(9, "Bà Kim Hoa?", "talkname9", 1);
    Talk(16, "Nhiều năm trước không biết vì lý do gì mà không chữa trị cho một ông Lá Bạc, sau này nghe tin ông ấy bị bệnh qua đời. Mấy ngày trước, vợ ông ấy là Kim Hoa bà nội đã tới Thung lũng Điệp và mang vợ ngươi đi. Cô ấy nói rằng cô ấy muốn tôi và vợ phải trải qua nỗi đau chia ly và cái chết. Than ôi, chỉ là lỗi của tôi mà tôi đã không cứu được ông Lá Bạc. Bây giờ võ kỹ của tôi còn thấp, tôi không thể đánh bại được cô ấy. Vợ anh không biết chuyện gì đang xảy ra nữa.", "talkname16", 0);
    Talk(9, "Bác Hồ, không sao đâu, đại ca của con rất giỏi võ công, chúng ta hãy đi cứu vợ con ngay bây giờ.", "talkname9", 1);
    Talk(0, "Thật sự! Đây chỉ là chuyện nhỏ thôi, tất cả là tại tôi. Bạn có biết bà cụ hoa vàng này sống ở đâu không?", "talkname0", 1);
    Talk(16, "Có vẻ như anh ta sống trên một hòn đảo nhỏ ở biển Hoa Đông, tên là Đảo Linh Xà.", "talkname16", 0);
    Talk(0, "Được rồi, hãy xem tôi làm ầm ĩ ở Đảo Linh Xà nhé.", "talkname0", 1);
	jyx2_ReplaceSceneObject("", "NPC/张无忌", "0");
    ModifyEvent(-2, -2, -2, -2, 94, -1, -1, -2, -2, -2, -2, -2, -2);
    ModifyEvent(73, 1, -2, -2, 104, -1, -1, -2, -2, -2, -2, -2, -2);
    ModifyEvent(73, 0, -2, -2, 101, -1, -1, -2, -2, -2, -2, -2, -2);
    ChangeMMapMusic(3);
do return end;
